#!/usr/bin/env python3
"""Generate uniform pagination adapters for selected list operations."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import tomllib


def snake(value: str) -> str:
    value = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    return value.lower()


def format_rust(source: str) -> str:
    return subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=source,
        text=True,
        check=True,
        capture_output=True,
    ).stdout


def selected(root: pathlib.Path, source_id: str) -> tuple[str, list[dict]]:
    if source_id == "API-2010":
        manifest = "codegen/coverage/rest-api-2010.toml"
        crate_name = "dialkit_api_generated"
    else:
        manifest = "codegen/coverage/rest-messaging-v1.toml"
        crate_name = "dialkit_messaging_generated"
    with (root / manifest).open("rb") as handle:
        rows = [
            row
            for row in tomllib.load(handle)["operation"]
            if row["operation_id"].startswith("List")
        ]
    return crate_name, rows


def return_type(source: str, symbol: str) -> str:
    match = re.search(
        rf"pub async fn {re.escape(symbol)}\(.*?\)\s*->\s*Result<\s*models::(\w+),\s*Error<",
        source,
        re.S,
    )
    if not match:
        raise ValueError(f"cannot resolve return type for {symbol}")
    return match.group(1)


def item_field(crate: pathlib.Path, response: str) -> tuple[str, str]:
    source = (crate / "src/models" / f"{snake(response)}.rs").read_text()
    matches = re.findall(
        r"pub (\w+):\s*Option<\s*Vec<\s*models::(\w+)\s*,?\s*>\s*,?\s*>", source
    )
    if len(matches) != 1:
        raise ValueError(f"{response}: expected one resource collection, found {matches}")
    return matches[0]


def generate(root: pathlib.Path, crate: pathlib.Path, source_id: str) -> tuple[str, str]:
    crate_name, rows = selected(root, source_id)
    adapters = []
    tests = []
    seen = set()
    for row in rows:
        module, symbol = row["generated_symbol"].split("::", 1)
        api_source = (crate / "src/apis" / f"{module}.rs").read_text()
        response = return_type(api_source, symbol)
        field, item = item_field(crate, response)
        continuation = (
            "self.next_page_uri.flatten()"
            if source_id == "API-2010"
            else "self.meta.and_then(|meta| meta.next_page_url.flatten())"
        )
        if response not in seen:
            adapters.append(
                f'''impl PageResponse for models::{response} {{
    type Item = models::{item};

    fn into_page(self) -> Page<Self::Item> {{
        Page {{ items: self.{field}.unwrap_or_default(), next_page_uri: {continuation} }}
    }}
}}
'''
            )
            seen.add(response)
        body = (
            f'r#"{{"{field}":[{{}}],"next_page_uri":"/next?PageToken=a%2Fb%2Bc%3D"}}"#'
            if source_id == "API-2010"
            else f'r#"{{"{field}":[{{}}],"meta":{{"next_page_url":"/next?PageToken=a%2Fb%2Bc%3D"}}}}"#'
        )
        tests.append(
            f'''#[test]
fn adapter_{snake(row["operation_id"])}() {{
    let response: models::{response} = serde_json::from_str({body}).unwrap();
    let page = PageResponse::into_page(response);
    assert_eq!(page.items.len(), 1);
    assert_eq!(page.next_page_uri.as_deref(), Some("/next?PageToken=a%2Fb%2Bc%3D"));
}}
'''
        )
    module_output = f'''// @generated by codegen/contracts/generate_pagination.py.
// DO NOT EDIT: update pinned contracts and rerun regeneration.

use crate::{{apis::configuration::Configuration, models}};
use dialkit_core::{{
    error::Error,
    pagination::{{Page, Pager}},
    request::RequestSpec,
    retry::OperationSafety,
}};
use serde::de::DeserializeOwned;

pub trait PageResponse: DeserializeOwned + Send + 'static {{
    type Item: Send + Unpin + 'static;
    fn into_page(self) -> Page<Self::Item>;
}}

/// Continues from a generated one-page response using opaque Twilio links.
/// The shared transport rejects malformed and cross-origin continuations and
/// `Pager` rejects repeated continuation links.
pub fn follow<P>(configuration: Configuration, first: P) -> Pager<P::Item>
where
    P: PageResponse,
{{
    let mut first = Some(first);
    Pager::new(move |continuation| {{
        let configuration = configuration.clone();
        let initial = first.take();
        Box::pin(async move {{
            let response = match (initial, continuation) {{
                (Some(response), None) => response,
                (_, Some(uri)) => {{
                    let request = RequestSpec {{
                        operation: "generated_list_continuation",
                        method: reqwest::Method::GET,
                        route_template: "/generated/pagination",
                        path: uri,
                        query: Vec::new(),
                        form: Vec::new(),
                        safety: OperationSafety::Read,
                    }};
                    configuration.client.execute_json::<P>(&request).await?
                }}
                (None, None) => return Err(Error::Validation("missing initial pagination response".into())),
            }};
            Ok(response.into_page())
        }})
    }})
}}

{''.join(adapters)}'''
    traversal = ""
    imports = f"use {crate_name}::{{models, pagination::PageResponse}};"
    if source_id == "API-2010":
        imports = f'''use {crate_name}::{{
    apis::configuration::Configuration,
    models,
    pagination::{{follow, PageResponse}},
}};
use dialkit_core::{{
    auth::{{AccountSid, Credentials}},
    error::Error,
    request::{{ClientConfiguration, HttpClient}},
    retry::RetryPolicy,
}};
use secrecy::SecretString;
use std::time::Duration;
use url::Url;
use wiremock::{{Mock, MockServer, ResponseTemplate, matchers::{{header_exists, method, path, query_param}}}};
'''
        traversal = r'''
fn configuration(server: &MockServer) -> Configuration {
    let client = HttpClient::new(ClientConfiguration {
        credentials: Credentials::account_token(
            AccountSid::new("ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa").unwrap(),
            SecretString::from("synthetic-token".to_owned()),
        ),
        base_url: Url::parse(&server.uri()).unwrap(),
        connect_timeout: Duration::from_secs(1),
        request_timeout: Duration::from_secs(2),
        retry_policy: RetryPolicy::conservative(),
        allow_http_for_tests: true,
    }).unwrap();
    Configuration::new(client)
}

#[tokio::test]
async fn generated_pager_handles_zero_and_multiple_pages_and_reserved_tokens() {
    let server = MockServer::start().await;
    let empty: models::ListCallResponse = serde_json::from_str(r#"{"calls":[]}"#).unwrap();
    assert!(follow(configuration(&server), empty).next().await.is_none());

    Mock::given(method("GET"))
        .and(path("/next"))
        .and(query_param("PageToken", "a/b+c="))
        .and(header_exists("authorization"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            r#"{"calls":[{},{}],"next_page_uri":null}"#,
            "application/json",
        ))
        .expect(1)
        .mount(&server)
        .await;
    let first: models::ListCallResponse = serde_json::from_str(
        r#"{"calls":[{}],"next_page_uri":"/next?PageToken=a%2Fb%2Bc%3D"}"#,
    ).unwrap();
    let mut pager = follow(configuration(&server), first);
    assert!(pager.next().await.unwrap().is_ok());
    assert!(pager.next().await.unwrap().is_ok());
    assert!(pager.next().await.unwrap().is_ok());
    assert!(pager.next().await.is_none());
}

#[tokio::test]
async fn generated_pager_rejects_loops_and_cross_origin_links() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path("/loop"))
        .respond_with(ResponseTemplate::new(200).set_body_raw(
            r#"{"calls":[],"next_page_uri":"/loop"}"#,
            "application/json",
        ))
        .expect(1)
        .mount(&server)
        .await;
    let looped: models::ListCallResponse = serde_json::from_str(
        r#"{"calls":[],"next_page_uri":"/loop"}"#,
    ).unwrap();
    assert!(matches!(follow(configuration(&server), looped).next().await, Some(Err(Error::Validation(message))) if message.contains("repeated")));

    let foreign: models::ListCallResponse = serde_json::from_str(
        r#"{"calls":[],"next_page_uri":"https://evil.invalid/next"}"#,
    ).unwrap();
    assert!(matches!(follow(configuration(&server), foreign).next().await, Some(Err(Error::Validation(message))) if message.contains("cross-origin")));
}
'''
    test_output = f'''// @generated by codegen/contracts/generate_pagination.py.
{imports}

{''.join(tests)}
{traversal}'''
    return format_rust(module_output), format_rust(test_output)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, required=True)
    parser.add_argument("--crate", type=pathlib.Path, required=True)
    parser.add_argument("--source", choices=["API-2010", "MSG-V1"], required=True)
    parser.add_argument("--test-output", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root, crate = args.root.resolve(), args.crate.resolve()
    module, tests = generate(root, crate, args.source)
    module_path = crate / "src/pagination.rs"
    lib = crate / "src/lib.rs"
    source = lib.read_text()
    if args.check:
        stale = not module_path.is_file() or module_path.read_text() != module
        if "pub mod pagination;" not in source:
            stale = True
        if args.test_output and (
            not args.test_output.is_file() or args.test_output.read_text() != tests
        ):
            stale = True
        if stale:
            print(f"stale generated pagination artifacts: {crate}")
        return int(stale)
    module_path.write_text(module)
    if "pub mod pagination;" not in source:
        source = source.replace("pub mod models;", "pub mod models;\npub mod pagination;")
        lib.write_text(source)
    if args.test_output:
        args.test_output.write_text(tests)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
