#!/usr/bin/env python3
"""Generate one signed verification test per webhook variant and encoding."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import tomllib


FAMILIES = {
    "voice-instruction": "VoiceInstruction",
    "call-progress": "CallProgress",
    "answering-machine": "AnsweringMachine",
    "twiml-action": "VoiceAction",
    "recording": "Recording",
    "conference": "Conference",
    "queue": "Queue",
    "gather": "Gather",
    "stream-siprec": "Stream",
    "transcription": "Transcription",
    "payment": "Payment",
    "user-defined-message": "UserDefinedMessage",
    "incoming-message": "IncomingMessage",
    "message-status": "MessageStatus",
    "messaging-service-routing": "MessagingServiceRouting",
    "json-verification": "MessageStatus",
}


def ident(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_").lower()


def generate(root: pathlib.Path) -> str:
    with (root / "codegen/coverage/webhook-families.toml").open("rb") as handle:
        manifest = tomllib.load(handle)
    cases = []
    for row in manifest["families"]:
        family = row["family"]
        for variant in row["variants"]:
            for encoding in row["encodings"]:
                case = f"contract_{ident(family)}_{ident(variant)}_{ident(encoding)}"
                kind = "Get" if encoding == "GET" else "Form" if encoding == "form" else "Json"
                variant_field = row.get("open_values", [])[0] if row.get("open_values") else ""
                cases.append(
                    f'''#[test]
fn {case}() {{
    verify_case(WebhookFamily::{FAMILIES[family]}, {family!r}, {variant!r}, {variant_field!r}, Encoding::{kind});
}}
'''.replace("'", '"')
                )
    source = r'''// @generated by codegen/contracts/generate_webhook_matrix.py.
// Each test is a distinct manifest family / variant / encoding contract.
use base64::{Engine as _, engine::general_purpose::STANDARD};
use dialkit::{FamilyJsonWebhookEvent, FamilyWebhookEvent, WebhookFamily, WebhookValidator};
use hmac::{Hmac, Mac as _};
use sha1::Sha1;
use sha2::{Digest as _, Sha256};

#[derive(Clone, Copy)]
enum Encoding { Get, Form, Json }

fn form_signature(token: &str, url: &str, pairs: &[(String, String)]) -> String {
    let mut sorted = pairs.to_vec();
    sorted.sort_by(|left, right| left.0.cmp(&right.0).then_with(|| left.1.cmp(&right.1)));
    let mut input = url.to_owned();
    for (name, value) in sorted { input.push_str(&name); input.push_str(&value); }
    let mut mac = Hmac::<Sha1>::new_from_slice(token.as_bytes()).unwrap();
    mac.update(input.as_bytes());
    STANDARD.encode(mac.finalize().into_bytes())
}

fn url_signature(token: &str, url: &str) -> String {
    let mut mac = Hmac::<Sha1>::new_from_slice(token.as_bytes()).unwrap();
    mac.update(url.as_bytes());
    STANDARD.encode(mac.finalize().into_bytes())
}

fn verify_case(family: WebhookFamily, family_name: &str, variant: &str, variant_field: &str, encoding: Encoding) {
    let token = "synthetic-matrix-token";
    let validator = WebhookValidator::new(token);
    let marker = format!("{family_name}:{variant}");
    match encoding {
        Encoding::Get | Encoding::Form => {
            let base_url = format!("https://example.test/hooks/{family_name}?fixed=a%2Bb");
            let mut pairs = family.known_fields().iter().map(|field| {
                let value = if field.as_str() == variant_field { variant.to_owned() } else { marker.clone() };
                (field.as_str().to_owned(), value)
            }).collect::<Vec<_>>();
            if !pairs.iter().any(|(name, _)| name == "CallSid") && !matches!(family, WebhookFamily::IncomingMessage | WebhookFamily::MessageStatus | WebhookFamily::MessagingServiceRouting) {
                pairs.push(("CallSid".into(), "CA00000000000000000000000000000000".into()));
            }
            if matches!(family, WebhookFamily::IncomingMessage | WebhookFamily::MessageStatus | WebhookFamily::MessagingServiceRouting) && !pairs.iter().any(|(name, _)| name == "MessageSid") {
                pairs.push(("MessageSid".into(), "SM00000000000000000000000000000000".into()));
            }
            pairs.push(("FutureField".into(), "first".into()));
            pairs.push(("FutureField".into(), "".into()));
            let query = url::form_urlencoded::Serializer::new(String::new())
                .extend_pairs(pairs.iter().map(|(name, value)| (name.as_str(), value.as_str())))
                .finish();
            let url = if matches!(encoding, Encoding::Get) { format!("{base_url}&{query}") } else { base_url.clone() };
            let signature = if matches!(encoding, Encoding::Get) { url_signature(token, &url) } else { form_signature(token, &url, &pairs) };
            let verified = if matches!(encoding, Encoding::Get) {
                validator.verify_get(family, &url, &signature).unwrap()
            } else {
                validator.verify_form(family, &url, &pairs, &signature).unwrap()
            };
            assert_eq!(verified.family(), family);
            let parsed = verified.parse_family_specific();
            assert_eq!(parsed.family(), family);
            assert_eq!(parsed.extras().iter().filter(|value| value.name() == "FutureField").count(), 2);
            assert!(!format!("{parsed:?}").contains(&marker));
            let typed = verified.parse_typed();
            assert_eq!(typed.known().len(), family.known_fields().len());
            assert!(typed.known().iter().all(|value| value.value() == (if value.field().as_str() == variant_field { variant } else { &marker })));
            match parsed {
                FamilyWebhookEvent::CallProgress(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::Recording(value) => {
                    assert_eq!(value.recording_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::Conference(value) => {
                    assert_eq!(value.conference_sid(), Some(marker.as_str()));
                    assert_eq!(value.event().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::MessageStatus(value) => {
                    assert_eq!(value.message_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                _ => {}
            }
            if family_name == "stream-siprec" {
                let siprec = validator.verify_form(WebhookFamily::Siprec, &url, &pairs, &signature).unwrap();
                assert_eq!(siprec.parse_family_specific().family(), WebhookFamily::Siprec);
            }
            if matches!(encoding, Encoding::Get) {
                assert!(validator.verify_get(family, &url, "aW52YWxpZA==").is_err());
                assert!(validator.verify_get(family, &url, "not-base64!").is_err());
                assert!(validator.verify_get(family, &url.replace("fixed=a%2Bb", "fixed=a+b"), &signature).is_err());
                assert!(validator.verify_get(family, &format!("{url}&FutureField=tampered"), &signature).is_err());
                let reordered = format!("{base_url}&FutureField=&{query}");
                assert!(validator.verify_get(family, &reordered, &signature).is_err());
                let decoded = url::Url::parse(&url).unwrap().query_pairs().skip(1).map(|(name, value)| (name.into_owned(), value.into_owned())).collect::<Vec<_>>();
                assert_eq!(decoded, pairs);
            } else {
                assert!(validator.verify_form(family, &url, &pairs, "aW52YWxpZA==").is_err());
                assert!(validator.verify_form(family, &url, &pairs, "not-base64!").is_err());
                let mut tampered = pairs.clone();
                tampered.push(("FutureField".into(), "tampered".into()));
                assert!(validator.verify_form(family, &url, &tampered, &signature).is_err());
            }
        }
        Encoding::Json => {
            let mut body = serde_json::Map::new();
            for field in family.known_fields() {
                if field.as_str() == "ChannelData" {
                    body.insert("ChannelData".into(), serde_json::json!({"future-channel": {"marker": marker}}));
                    continue;
                }
                let value = if field.as_str() == variant_field { variant.to_owned() } else { marker.clone() };
                body.insert(field.as_str().into(), serde_json::Value::String(value));
            }
            body.insert("FutureProperty".into(), serde_json::json!({"nested": true}));
            let body = serde_json::to_vec(&body).unwrap();
            let digest = Sha256::digest(&body).iter().map(|byte| format!("{byte:02x}")).collect::<String>();
            let url = format!("https://example.test/hooks/{family_name}?bodySHA256={digest}");
            let signature = url_signature(token, &url);
            let verified = validator.verify_json(family, &url, &body, &signature).unwrap();
            let parsed = verified.parse_typed();
            assert_eq!(parsed.family(), family);
            assert_eq!(parsed.extras()["FutureProperty"]["nested"], true);
            let projected = verified.parse_family_specific().expect("JSON-capable family projection");
            assert_eq!(projected.family(), family);
            assert_eq!(projected.extras()["FutureProperty"]["nested"], true);
            assert!(!format!("{projected:?}").contains(&marker));
            match projected {
                FamilyJsonWebhookEvent::Stream(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.stream_event(), Some(if variant_field == "StreamEvent" { variant } else { marker.as_str() }));
                }
                FamilyJsonWebhookEvent::Siprec(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.siprec_event(), Some(marker.as_str()));
                }
                FamilyJsonWebhookEvent::Transcription(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.transcription_event(), Some(if variant_field == "TranscriptionEvent" { variant } else { marker.as_str() }));
                }
                FamilyJsonWebhookEvent::UserDefinedMessage(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.event(), Some(if variant_field == "Event" { variant } else { marker.as_str() }));
                    assert_eq!(value.payload().and_then(serde_json::Value::as_str), Some(marker.as_str()));
                }
                FamilyJsonWebhookEvent::MessageStatus(value) => {
                    assert_eq!(value.message_sid(), Some(marker.as_str()));
                    assert_eq!(value.channel_data().unwrap()["future-channel"]["marker"], marker);
                    assert!(!value.extras().contains_key("ChannelData"));
                    assert_eq!(value.status().unwrap().as_str(), if variant_field == "MessageStatus" { variant } else { marker.as_str() });
                }
                _ => unreachable!("unexpected JSON family"),
            }
            if family_name == "stream-siprec" {
                let siprec = validator.verify_json(WebhookFamily::Siprec, &url, &body, &signature).unwrap();
                assert!(matches!(siprec.parse_family_specific(), Some(FamilyJsonWebhookEvent::Siprec(_))));
            }
            assert!(validator.verify_json(family, &url, &body, "aW52YWxpZA==").is_err());
            assert!(validator.verify_json(family, &url, b"{}", &signature).is_err());
            let malformed = b"{";
            let malformed_digest = Sha256::digest(malformed).iter().map(|byte| format!("{byte:02x}")).collect::<String>();
            let malformed_url = format!("https://example.test/hooks/{family_name}?bodySHA256={malformed_digest}");
            let malformed_signature = url_signature(token, &malformed_url);
            assert!(validator.verify_json(family, &malformed_url, malformed, &malformed_signature).is_err());
        }
    }
}

'''
    source += "\n".join(cases)
    return subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=source,
        text=True,
        check=True,
        capture_output=True,
    ).stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / "crates/client/tests/webhook_runtime_matrix.rs"
    generated = generate(root)
    if args.check:
        if not output.is_file() or output.read_text() != generated:
            print(f"stale webhook runtime matrix: {output.relative_to(root)}")
            return 1
    else:
        output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
