[package]
name = "dialkit-api-generated"
description = "Generated Twilio api_v2010 companion for dialkit"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
default = ["rustls-tls"]
rustls-tls = ["dialkit-core/rustls-tls"]
native-tls = ["dialkit-core/native-tls"]

[dependencies]
chrono.workspace = true
dialkit-core = { version = "0.1.0", path = "../client-core", default-features = false }
reqwest = { workspace = true, features = ["multipart"] }
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
serde_with.workspace = true
url.workspace = true

[dev-dependencies]
base64.workspace = true
secrecy.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = "0.6.5"

[lints]
workspace = true
