// @generated by codegen/contracts/generate_webhook_matrix.py.
// Each test is a distinct manifest family / variant / encoding contract.
use base64::{Engine as _, engine::general_purpose::STANDARD};
use dialkit::{FamilyJsonWebhookEvent, FamilyWebhookEvent, WebhookFamily, WebhookValidator};
use hmac::{Hmac, Mac as _};
use sha1::Sha1;
use sha2::{Digest as _, Sha256};

#[derive(Clone, Copy)]
enum Encoding {
    Get,
    Form,
    Json,
}

fn form_signature(token: &str, url: &str, pairs: &[(String, String)]) -> String {
    let mut sorted = pairs.to_vec();
    sorted.sort_by(|left, right| left.0.cmp(&right.0).then_with(|| left.1.cmp(&right.1)));
    let mut input = url.to_owned();
    for (name, value) in sorted {
        input.push_str(&name);
        input.push_str(&value);
    }
    let mut mac = Hmac::<Sha1>::new_from_slice(token.as_bytes()).unwrap();
    mac.update(input.as_bytes());
    STANDARD.encode(mac.finalize().into_bytes())
}

fn url_signature(token: &str, url: &str) -> String {
    let mut mac = Hmac::<Sha1>::new_from_slice(token.as_bytes()).unwrap();
    mac.update(url.as_bytes());
    STANDARD.encode(mac.finalize().into_bytes())
}

fn verify_case(
    family: WebhookFamily,
    family_name: &str,
    variant: &str,
    variant_field: &str,
    encoding: Encoding,
) {
    let token = "synthetic-matrix-token";
    let validator = WebhookValidator::new(token);
    let marker = format!("{family_name}:{variant}");
    match encoding {
        Encoding::Get | Encoding::Form => {
            let base_url = format!("https://example.test/hooks/{family_name}?fixed=a%2Bb");
            let mut pairs = family
                .known_fields()
                .iter()
                .map(|field| {
                    let value = if field.as_str() == variant_field {
                        variant.to_owned()
                    } else {
                        marker.clone()
                    };
                    (field.as_str().to_owned(), value)
                })
                .collect::<Vec<_>>();
            if !pairs.iter().any(|(name, _)| name == "CallSid")
                && !matches!(
                    family,
                    WebhookFamily::IncomingMessage
                        | WebhookFamily::MessageStatus
                        | WebhookFamily::MessagingServiceRouting
                )
            {
                pairs.push((
                    "CallSid".into(),
                    "CA00000000000000000000000000000000".into(),
                ));
            }
            if matches!(
                family,
                WebhookFamily::IncomingMessage
                    | WebhookFamily::MessageStatus
                    | WebhookFamily::MessagingServiceRouting
            ) && !pairs.iter().any(|(name, _)| name == "MessageSid")
            {
                pairs.push((
                    "MessageSid".into(),
                    "SM00000000000000000000000000000000".into(),
                ));
            }
            pairs.push(("FutureField".into(), "first".into()));
            pairs.push(("FutureField".into(), "".into()));
            let query = url::form_urlencoded::Serializer::new(String::new())
                .extend_pairs(
                    pairs
                        .iter()
                        .map(|(name, value)| (name.as_str(), value.as_str())),
                )
                .finish();
            let url = if matches!(encoding, Encoding::Get) {
                format!("{base_url}&{query}")
            } else {
                base_url.clone()
            };
            let signature = if matches!(encoding, Encoding::Get) {
                url_signature(token, &url)
            } else {
                form_signature(token, &url, &pairs)
            };
            let verified = if matches!(encoding, Encoding::Get) {
                validator.verify_get(family, &url, &signature).unwrap()
            } else {
                validator
                    .verify_form(family, &url, &pairs, &signature)
                    .unwrap()
            };
            assert_eq!(verified.family(), family);
            let parsed = verified.parse_family_specific();
            assert_eq!(parsed.family(), family);
            assert_eq!(
                parsed
                    .extras()
                    .iter()
                    .filter(|value| value.name() == "FutureField")
                    .count(),
                2
            );
            assert!(!format!("{parsed:?}").contains(&marker));
            let typed = verified.parse_typed();
            assert_eq!(typed.known().len(), family.known_fields().len());
            assert!(typed.known().iter().all(|value| value.value()
                == (if value.field().as_str() == variant_field {
                    variant
                } else {
                    &marker
                })));
            match parsed {
                FamilyWebhookEvent::CallProgress(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::Recording(value) => {
                    assert_eq!(value.recording_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::Conference(value) => {
                    assert_eq!(value.conference_sid(), Some(marker.as_str()));
                    assert_eq!(value.event().unwrap().as_str(), variant);
                }
                FamilyWebhookEvent::MessageStatus(value) => {
                    assert_eq!(value.message_sid(), Some(marker.as_str()));
                    assert_eq!(value.status().unwrap().as_str(), variant);
                }
                _ => {}
            }
            if family_name == "stream-siprec" {
                let siprec = validator
                    .verify_form(WebhookFamily::Siprec, &url, &pairs, &signature)
                    .unwrap();
                assert_eq!(
                    siprec.parse_family_specific().family(),
                    WebhookFamily::Siprec
                );
            }
            if matches!(encoding, Encoding::Get) {
                assert!(validator.verify_get(family, &url, "aW52YWxpZA==").is_err());
                assert!(validator.verify_get(family, &url, "not-base64!").is_err());
                assert!(
                    validator
                        .verify_get(family, &url.replace("fixed=a%2Bb", "fixed=a+b"), &signature)
                        .is_err()
                );
                assert!(
                    validator
                        .verify_get(family, &format!("{url}&FutureField=tampered"), &signature)
                        .is_err()
                );
                let reordered = format!("{base_url}&FutureField=&{query}");
                assert!(
                    validator
                        .verify_get(family, &reordered, &signature)
                        .is_err()
                );
                let decoded = url::Url::parse(&url)
                    .unwrap()
                    .query_pairs()
                    .skip(1)
                    .map(|(name, value)| (name.into_owned(), value.into_owned()))
                    .collect::<Vec<_>>();
                assert_eq!(decoded, pairs);
            } else {
                assert!(
                    validator
                        .verify_form(family, &url, &pairs, "aW52YWxpZA==")
                        .is_err()
                );
                assert!(
                    validator
                        .verify_form(family, &url, &pairs, "not-base64!")
                        .is_err()
                );
                let mut tampered = pairs.clone();
                tampered.push(("FutureField".into(), "tampered".into()));
                assert!(
                    validator
                        .verify_form(family, &url, &tampered, &signature)
                        .is_err()
                );
            }
        }
        Encoding::Json => {
            let mut body = serde_json::Map::new();
            for field in family.known_fields() {
                if field.as_str() == "ChannelData" {
                    body.insert(
                        "ChannelData".into(),
                        serde_json::json!({"future-channel": {"marker": marker}}),
                    );
                    continue;
                }
                let value = if field.as_str() == variant_field {
                    variant.to_owned()
                } else {
                    marker.clone()
                };
                body.insert(field.as_str().into(), serde_json::Value::String(value));
            }
            body.insert("FutureProperty".into(), serde_json::json!({"nested": true}));
            let body = serde_json::to_vec(&body).unwrap();
            let digest = Sha256::digest(&body)
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<String>();
            let url = format!("https://example.test/hooks/{family_name}?bodySHA256={digest}");
            let signature = url_signature(token, &url);
            let verified = validator
                .verify_json(family, &url, &body, &signature)
                .unwrap();
            let parsed = verified.parse_typed();
            assert_eq!(parsed.family(), family);
            assert_eq!(parsed.extras()["FutureProperty"]["nested"], true);
            let projected = verified
                .parse_family_specific()
                .expect("JSON-capable family projection");
            assert_eq!(projected.family(), family);
            assert_eq!(projected.extras()["FutureProperty"]["nested"], true);
            assert!(!format!("{projected:?}").contains(&marker));
            match projected {
                FamilyJsonWebhookEvent::Stream(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(
                        value.stream_event(),
                        Some(if variant_field == "StreamEvent" {
                            variant
                        } else {
                            marker.as_str()
                        })
                    );
                }
                FamilyJsonWebhookEvent::Siprec(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(value.siprec_event(), Some(marker.as_str()));
                }
                FamilyJsonWebhookEvent::Transcription(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(
                        value.transcription_event(),
                        Some(if variant_field == "TranscriptionEvent" {
                            variant
                        } else {
                            marker.as_str()
                        })
                    );
                }
                FamilyJsonWebhookEvent::UserDefinedMessage(value) => {
                    assert_eq!(value.call_sid(), Some(marker.as_str()));
                    assert_eq!(
                        value.event(),
                        Some(if variant_field == "Event" {
                            variant
                        } else {
                            marker.as_str()
                        })
                    );
                    assert_eq!(
                        value.payload().and_then(serde_json::Value::as_str),
                        Some(marker.as_str())
                    );
                }
                FamilyJsonWebhookEvent::MessageStatus(value) => {
                    assert_eq!(value.message_sid(), Some(marker.as_str()));
                    assert_eq!(
                        value.channel_data().unwrap()["future-channel"]["marker"],
                        marker
                    );
                    assert!(!value.extras().contains_key("ChannelData"));
                    assert_eq!(
                        value.status().unwrap().as_str(),
                        if variant_field == "MessageStatus" {
                            variant
                        } else {
                            marker.as_str()
                        }
                    );
                }
                _ => unreachable!("unexpected JSON family"),
            }
            if family_name == "stream-siprec" {
                let siprec = validator
                    .verify_json(WebhookFamily::Siprec, &url, &body, &signature)
                    .unwrap();
                assert!(matches!(
                    siprec.parse_family_specific(),
                    Some(FamilyJsonWebhookEvent::Siprec(_))
                ));
            }
            assert!(
                validator
                    .verify_json(family, &url, &body, "aW52YWxpZA==")
                    .is_err()
            );
            assert!(
                validator
                    .verify_json(family, &url, b"{}", &signature)
                    .is_err()
            );
            let malformed = b"{";
            let malformed_digest = Sha256::digest(malformed)
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<String>();
            let malformed_url =
                format!("https://example.test/hooks/{family_name}?bodySHA256={malformed_digest}");
            let malformed_signature = url_signature(token, &malformed_url);
            assert!(
                validator
                    .verify_json(family, &malformed_url, malformed, &malformed_signature)
                    .is_err()
            );
        }
    }
}

#[test]
fn contract_voice_instruction_inbound_get() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "inbound",
        "CallStatus",
        Encoding::Get,
    );
}

#[test]
fn contract_voice_instruction_inbound_form() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "inbound",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_voice_instruction_outbound_answer_get() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "outbound-answer",
        "CallStatus",
        Encoding::Get,
    );
}

#[test]
fn contract_voice_instruction_outbound_answer_form() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "outbound-answer",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_voice_instruction_redirect_get() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "redirect",
        "CallStatus",
        Encoding::Get,
    );
}

#[test]
fn contract_voice_instruction_redirect_form() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "redirect",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_voice_instruction_fallback_get() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "fallback",
        "CallStatus",
        Encoding::Get,
    );
}

#[test]
fn contract_voice_instruction_fallback_form() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "fallback",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_voice_instruction_sip_get() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "sip",
        "CallStatus",
        Encoding::Get,
    );
}

#[test]
fn contract_voice_instruction_sip_form() {
    verify_case(
        WebhookFamily::VoiceInstruction,
        "voice-instruction",
        "sip",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_initiated_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "initiated",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_ringing_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "ringing",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_answered_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "answered",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_completed_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "completed",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_busy_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "busy",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_failed_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "failed",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_no_answer_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "no-answer",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_call_progress_canceled_form() {
    verify_case(
        WebhookFamily::CallProgress,
        "call-progress",
        "canceled",
        "CallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_answering_machine_result_form() {
    verify_case(
        WebhookFamily::AnsweringMachine,
        "answering-machine",
        "result",
        "AnsweredBy",
        Encoding::Form,
    );
}

#[test]
fn contract_answering_machine_unknown_form() {
    verify_case(
        WebhookFamily::AnsweringMachine,
        "answering-machine",
        "unknown",
        "AnsweredBy",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_connect_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Connect",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_dial_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Dial",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_enqueue_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Enqueue",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_gather_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Gather",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_pay_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Pay",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_record_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Record",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_redirect_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Redirect",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_refer_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Refer",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_twiml_action_message_form() {
    verify_case(
        WebhookFamily::VoiceAction,
        "twiml-action",
        "Message",
        "DialCallStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_recording_in_progress_form() {
    verify_case(
        WebhookFamily::Recording,
        "recording",
        "in-progress",
        "RecordingStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_recording_completed_form() {
    verify_case(
        WebhookFamily::Recording,
        "recording",
        "completed",
        "RecordingStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_recording_absent_form() {
    verify_case(
        WebhookFamily::Recording,
        "recording",
        "absent",
        "RecordingStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_start_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "start",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_end_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "end",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_join_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "join",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_leave_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "leave",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_mute_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "mute",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_hold_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "hold",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_conference_speaker_form() {
    verify_case(
        WebhookFamily::Conference,
        "conference",
        "speaker",
        "StatusCallbackEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_queue_enqueue_form() {
    verify_case(
        WebhookFamily::Queue,
        "queue",
        "enqueue",
        "QueueResult",
        Encoding::Form,
    );
}

#[test]
fn contract_queue_wait_form() {
    verify_case(
        WebhookFamily::Queue,
        "queue",
        "wait",
        "QueueResult",
        Encoding::Form,
    );
}

#[test]
fn contract_queue_leave_form() {
    verify_case(
        WebhookFamily::Queue,
        "queue",
        "leave",
        "QueueResult",
        Encoding::Form,
    );
}

#[test]
fn contract_queue_dequeue_form() {
    verify_case(
        WebhookFamily::Queue,
        "queue",
        "dequeue",
        "QueueResult",
        Encoding::Form,
    );
}

#[test]
fn contract_gather_final_form() {
    verify_case(WebhookFamily::Gather, "gather", "final", "", Encoding::Form);
}

#[test]
fn contract_gather_partial_speech_form() {
    verify_case(
        WebhookFamily::Gather,
        "gather",
        "partial-speech",
        "",
        Encoding::Form,
    );
}

#[test]
fn contract_stream_siprec_start_form() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "start",
        "StreamEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_stream_siprec_start_json() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "start",
        "StreamEvent",
        Encoding::Json,
    );
}

#[test]
fn contract_stream_siprec_stop_form() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "stop",
        "StreamEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_stream_siprec_stop_json() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "stop",
        "StreamEvent",
        Encoding::Json,
    );
}

#[test]
fn contract_stream_siprec_error_form() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "error",
        "StreamEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_stream_siprec_error_json() {
    verify_case(
        WebhookFamily::Stream,
        "stream-siprec",
        "error",
        "StreamEvent",
        Encoding::Json,
    );
}

#[test]
fn contract_transcription_status_form() {
    verify_case(
        WebhookFamily::Transcription,
        "transcription",
        "status",
        "TranscriptionEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_transcription_status_json() {
    verify_case(
        WebhookFamily::Transcription,
        "transcription",
        "status",
        "TranscriptionEvent",
        Encoding::Json,
    );
}

#[test]
fn contract_transcription_result_form() {
    verify_case(
        WebhookFamily::Transcription,
        "transcription",
        "result",
        "TranscriptionEvent",
        Encoding::Form,
    );
}

#[test]
fn contract_transcription_result_json() {
    verify_case(
        WebhookFamily::Transcription,
        "transcription",
        "result",
        "TranscriptionEvent",
        Encoding::Json,
    );
}

#[test]
fn contract_payment_action_form() {
    verify_case(
        WebhookFamily::Payment,
        "payment",
        "action",
        "Result",
        Encoding::Form,
    );
}

#[test]
fn contract_payment_status_form() {
    verify_case(
        WebhookFamily::Payment,
        "payment",
        "status",
        "Result",
        Encoding::Form,
    );
}

#[test]
fn contract_user_defined_message_subscription_delivery_form() {
    verify_case(
        WebhookFamily::UserDefinedMessage,
        "user-defined-message",
        "subscription-delivery",
        "Event",
        Encoding::Form,
    );
}

#[test]
fn contract_user_defined_message_subscription_delivery_json() {
    verify_case(
        WebhookFamily::UserDefinedMessage,
        "user-defined-message",
        "subscription-delivery",
        "Event",
        Encoding::Json,
    );
}

#[test]
fn contract_incoming_message_sms_get() {
    verify_case(
        WebhookFamily::IncomingMessage,
        "incoming-message",
        "sms",
        "",
        Encoding::Get,
    );
}

#[test]
fn contract_incoming_message_sms_form() {
    verify_case(
        WebhookFamily::IncomingMessage,
        "incoming-message",
        "sms",
        "",
        Encoding::Form,
    );
}

#[test]
fn contract_incoming_message_mms_get() {
    verify_case(
        WebhookFamily::IncomingMessage,
        "incoming-message",
        "mms",
        "",
        Encoding::Get,
    );
}

#[test]
fn contract_incoming_message_mms_form() {
    verify_case(
        WebhookFamily::IncomingMessage,
        "incoming-message",
        "mms",
        "",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_accepted_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "accepted",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_accepted_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "accepted",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_scheduled_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "scheduled",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_scheduled_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "scheduled",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_canceled_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "canceled",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_canceled_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "canceled",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_queued_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "queued",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_queued_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "queued",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_sending_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "sending",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_sending_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "sending",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_sent_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "sent",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_sent_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "sent",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_receiving_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "receiving",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_receiving_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "receiving",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_received_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "received",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_received_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "received",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_delivered_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "delivered",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_delivered_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "delivered",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_undelivered_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "undelivered",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_undelivered_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "undelivered",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_failed_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "failed",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_failed_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "failed",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_read_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "read",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_read_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "read",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_message_status_unknown_form() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "unknown",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_message_status_unknown_json() {
    verify_case(
        WebhookFamily::MessageStatus,
        "message-status",
        "unknown",
        "MessageStatus",
        Encoding::Json,
    );
}

#[test]
fn contract_messaging_service_routing_primary_form() {
    verify_case(
        WebhookFamily::MessagingServiceRouting,
        "messaging-service-routing",
        "primary",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_messaging_service_routing_fallback_form() {
    verify_case(
        WebhookFamily::MessagingServiceRouting,
        "messaging-service-routing",
        "fallback",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_messaging_service_routing_status_form() {
    verify_case(
        WebhookFamily::MessagingServiceRouting,
        "messaging-service-routing",
        "status",
        "MessageStatus",
        Encoding::Form,
    );
}

#[test]
fn contract_json_verification_any_supported_family_json_bodysha256() {
    verify_case(
        WebhookFamily::MessageStatus,
        "json-verification",
        "any-supported-family",
        "",
        Encoding::Json,
    );
}
