// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// BrandRegistrationsEnumStatus : Brand Registration status. One of \"PENDING\", \"APPROVED\", \"FAILED\", \"IN_REVIEW\", \"DELETION_PENDING\", \"DELETION_FAILED\", \"SUSPENDED\".
/// Brand Registration status. One of \"PENDING\", \"APPROVED\", \"FAILED\", \"IN_REVIEW\", \"DELETION_PENDING\", \"DELETION_FAILED\", \"SUSPENDED\".
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrandRegistrationsEnumStatus {
    Pending,
    Approved,
    Failed,
    InReview,
    DeletionPending,
    DeletionFailed,
    Suspended,

    Unknown(String),
}

impl BrandRegistrationsEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Pending => "PENDING",
            Self::Approved => "APPROVED",
            Self::Failed => "FAILED",
            Self::InReview => "IN_REVIEW",
            Self::DeletionPending => "DELETION_PENDING",
            Self::DeletionFailed => "DELETION_FAILED",
            Self::Suspended => "SUSPENDED",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for BrandRegistrationsEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for BrandRegistrationsEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "PENDING" => Self::Pending,
            "APPROVED" => Self::Approved,
            "FAILED" => Self::Failed,
            "IN_REVIEW" => Self::InReview,
            "DELETION_PENDING" => Self::DeletionPending,
            "DELETION_FAILED" => Self::DeletionFailed,
            "SUSPENDED" => Self::Suspended,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for BrandRegistrationsEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for BrandRegistrationsEnumStatus {
    fn default() -> BrandRegistrationsEnumStatus {
        Self::Pending
    }
}
