// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// BrandVettingEnumVettingProvider : The third-party provider that has conducted the vetting. One of “CampaignVerify” (Campaign Verify tokens) or “AEGIS” (Secondary Vetting).
/// The third-party provider that has conducted the vetting. One of “CampaignVerify” (Campaign Verify tokens) or “AEGIS” (Secondary Vetting).
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrandVettingEnumVettingProvider {
    CampaignVerify,
    Aegis,

    Unknown(String),
}

impl BrandVettingEnumVettingProvider {
    pub fn as_str(&self) -> &str {
        match self {
            Self::CampaignVerify => "campaign-verify",
            Self::Aegis => "aegis",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for BrandVettingEnumVettingProvider {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for BrandVettingEnumVettingProvider {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "campaign-verify" => Self::CampaignVerify,
            "aegis" => Self::Aegis,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for BrandVettingEnumVettingProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for BrandVettingEnumVettingProvider {
    fn default() -> BrandVettingEnumVettingProvider {
        Self::CampaignVerify
    }
}
