// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// BrandRegistrationsEnumIdentityStatus : When a brand is registered, TCR will attempt to verify the identity of the brand based on the supplied information.
/// When a brand is registered, TCR will attempt to verify the identity of the brand based on the supplied information.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrandRegistrationsEnumIdentityStatus {
    SelfDeclared,
    Unverified,
    Verified,
    VettedVerified,

    Unknown(String),
}

impl BrandRegistrationsEnumIdentityStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::SelfDeclared => "SELF_DECLARED",
            Self::Unverified => "UNVERIFIED",
            Self::Verified => "VERIFIED",
            Self::VettedVerified => "VETTED_VERIFIED",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for BrandRegistrationsEnumIdentityStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for BrandRegistrationsEnumIdentityStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "SELF_DECLARED" => Self::SelfDeclared,
            "UNVERIFIED" => Self::Unverified,
            "VERIFIED" => Self::Verified,
            "VETTED_VERIFIED" => Self::VettedVerified,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for BrandRegistrationsEnumIdentityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for BrandRegistrationsEnumIdentityStatus {
    fn default() -> BrandRegistrationsEnumIdentityStatus {
        Self::SelfDeclared
    }
}
