// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBrandRegistrationsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::MessagingV1BrandRegistrations>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListBrandRegistrationsResponse {
    pub fn new() -> ListBrandRegistrationsResponse {
        ListBrandRegistrationsResponse {
            data: None,
            meta: None,
        }
    }
}
