// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListChannelSenderResponse {
    #[serde(rename = "senders", skip_serializing_if = "Option::is_none")]
    pub senders: Option<Vec<models::MessagingV1ServiceChannelSender>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListChannelSenderResponse {
    pub fn new() -> ListChannelSenderResponse {
        ListChannelSenderResponse {
            senders: None,
            meta: None,
        }
    }
}
