// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDestinationAlphaSenderResponse {
    #[serde(rename = "alpha_senders", skip_serializing_if = "Option::is_none")]
    pub alpha_senders: Option<Vec<models::MessagingV1ServiceDestinationAlphaSender>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListDestinationAlphaSenderResponse {
    pub fn new() -> ListDestinationAlphaSenderResponse {
        ListDestinationAlphaSenderResponse {
            alpha_senders: None,
            meta: None,
        }
    }
}
