// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPhoneNumberResponse {
    #[serde(rename = "phone_numbers", skip_serializing_if = "Option::is_none")]
    pub phone_numbers: Option<Vec<models::MessagingV1ServicePhoneNumber>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListPhoneNumberResponse {
    pub fn new() -> ListPhoneNumberResponse {
        ListPhoneNumberResponse {
            phone_numbers: None,
            meta: None,
        }
    }
}
