// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUsAppToPersonResponse {
    #[serde(rename = "compliance", skip_serializing_if = "Option::is_none")]
    pub compliance: Option<Vec<models::MessagingV1ServiceUsAppToPersonResponse>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListUsAppToPersonResponse {
    pub fn new() -> ListUsAppToPersonResponse {
        ListUsAppToPersonResponse {
            compliance: None,
            meta: None,
        }
    }
}
