// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServiceResponse {
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<models::MessagingV1Service>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListServiceResponse {
    pub fn new() -> ListServiceResponse {
        ListServiceResponse {
            services: None,
            meta: None,
        }
    }
}
