// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTollfreeVerificationResponse {
    #[serde(rename = "verifications", skip_serializing_if = "Option::is_none")]
    pub verifications: Option<Vec<models::MessagingV1TollfreeVerification>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ListAlphaSenderResponseMeta>>,
}

impl ListTollfreeVerificationResponse {
    pub fn new() -> ListTollfreeVerificationResponse {
        ListTollfreeVerificationResponse {
            verifications: None,
            meta: None,
        }
    }
}
