// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1BrandRegistrationsBrandRegistrationOtp {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The unique string to identify Brand Registration of Sole Proprietor Brand
    #[serde(
        rename = "brand_registration_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_registration_sid: Option<Option<String>>,
}

impl MessagingV1BrandRegistrationsBrandRegistrationOtp {
    pub fn new() -> MessagingV1BrandRegistrationsBrandRegistrationOtp {
        MessagingV1BrandRegistrationsBrandRegistrationOtp {
            account_sid: None,
            brand_registration_sid: None,
        }
    }
}
