// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceDestinationAlphaSender {
    /// The unique string that we created to identify the AlphaSender resource.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AlphaSender resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with.
    #[serde(
        rename = "service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_sid: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The Alphanumeric Sender ID string.
    #[serde(
        rename = "alpha_sender",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub alpha_sender: Option<Option<String>>,
    /// An array of values that describe whether the number can receive calls or messages. Can be: `SMS`.
    #[serde(
        rename = "capabilities",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub capabilities: Option<Option<Vec<String>>>,
    /// The absolute URL of the AlphaSender resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// The Two Character ISO Country Code the Alphanumeric Sender ID will be used for. For Default Alpha Senders that work across countries, this value will be an empty string
    #[serde(
        rename = "iso_country_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub iso_country_code: Option<Option<String>>,
}

impl MessagingV1ServiceDestinationAlphaSender {
    pub fn new() -> MessagingV1ServiceDestinationAlphaSender {
        MessagingV1ServiceDestinationAlphaSender {
            sid: None,
            account_sid: None,
            service_sid: None,
            date_created: None,
            date_updated: None,
            alpha_sender: None,
            capabilities: None,
            url: None,
            iso_country_code: None,
        }
    }
}
