// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceUsAppToPersonV2 {
    /// The unique string that identifies a US A2P Compliance resource `QE2c6890da8086d771620e9b13fadeba0b`.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the Campaign belongs to.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The unique string to identify the A2P brand.
    #[serde(
        rename = "brand_registration_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_registration_sid: Option<Option<String>>,
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with.
    #[serde(
        rename = "messaging_service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub messaging_service_sid: Option<Option<String>>,
    /// A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// An array of sample message strings, min two and max five. Min length for each sample: 20 chars. Max length for each sample: 1024 chars.
    #[serde(
        rename = "message_samples",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_samples: Option<Option<Vec<String>>>,
    /// A2P Campaign Use Case. Examples: [ 2FA, EMERGENCY, MARKETING, SOLE_PROPRIETOR...]. SOLE_PROPRIETOR campaign use cases can only be created by SOLE_PROPRIETOR Brands, and there can only be one SOLE_PROPRIETOR campaign created per SOLE_PROPRIETOR Brand.
    #[serde(
        rename = "us_app_to_person_usecase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub us_app_to_person_usecase: Option<Option<String>>,
    /// Indicate that this SMS campaign will send messages that contain links.
    #[serde(
        rename = "has_embedded_links",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_embedded_links: Option<Option<bool>>,
    /// Indicates that this SMS campaign will send messages that contain phone numbers.
    #[serde(
        rename = "has_embedded_phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_embedded_phone: Option<Option<bool>>,
    /// A boolean that specifies whether campaign has Subscriber Optin or not.
    #[serde(
        rename = "subscriber_opt_in",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscriber_opt_in: Option<Option<bool>>,
    /// A boolean that specifies whether campaign is age gated or not.
    #[serde(
        rename = "age_gated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub age_gated: Option<Option<bool>>,
    /// A boolean that specifies whether campaign allows direct lending or not.
    #[serde(
        rename = "direct_lending",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub direct_lending: Option<Option<bool>>,
    /// Campaign status. Examples: IN_PROGRESS, VERIFIED, FAILED.
    #[serde(
        rename = "campaign_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_status: Option<Option<String>>,
    /// The Campaign Registry (TCR) Campaign ID.
    #[serde(
        rename = "campaign_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub campaign_id: Option<Option<String>>,
    /// Indicates whether the campaign was registered externally or not.
    #[serde(
        rename = "is_externally_registered",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_externally_registered: Option<Option<bool>>,
    /// Rate limit and/or classification set by each carrier, Ex. AT&T or T-Mobile.
    #[serde(
        rename = "rate_limits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rate_limits: Option<Option<serde_json::Value>>,
    /// Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum.
    #[serde(
        rename = "message_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_flow: Option<Option<String>>,
    /// If end users can text in a keyword to start receiving messages from this campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. This field is required if end users can text in a keyword to start receiving messages from this campaign. 20 character minimum. 320 character maximum.
    #[serde(
        rename = "opt_in_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_in_message: Option<Option<String>>,
    /// Upon receiving the opt-out keywords from the end users, Twilio customers are expected to send back an auto-generated response, which must provide acknowledgment of the opt-out request and confirmation that no further messages will be sent. It is also recommended that these opt-out messages include the brand name. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
    #[serde(
        rename = "opt_out_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_out_message: Option<Option<String>>,
    /// When customers receive the help keywords from their end users, Twilio customers are expected to send back an auto-generated response; this may include the brand name and additional support contact information. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
    #[serde(
        rename = "help_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub help_message: Option<Option<String>>,
    /// If end users can text in a keyword to start receiving messages from this campaign, those keywords must be provided. This field is required if end users can text in a keyword to start receiving messages from this campaign. Values must be alphanumeric. 255 character maximum.
    #[serde(
        rename = "opt_in_keywords",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_in_keywords: Option<Option<Vec<String>>>,
    /// End users should be able to text in a keyword to stop receiving messages from this campaign. Those keywords must be provided. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
    #[serde(
        rename = "opt_out_keywords",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_out_keywords: Option<Option<Vec<String>>>,
    /// End users should be able to text in a keyword to receive help. Those keywords must be provided as part of the campaign registration request. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
    #[serde(
        rename = "help_keywords",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub help_keywords: Option<Option<Vec<String>>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The absolute URL of the US App to Person resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// A boolean that specifies whether campaign is a mock or not. Mock campaigns will be automatically created if using a mock brand. Mock campaigns should only be used for testing purposes.
    #[serde(
        rename = "mock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mock: Option<Option<bool>>,
    /// Details indicating why a campaign registration failed. These errors can indicate one or more fields that were incorrect or did not meet review requirements.
    #[serde(
        rename = "errors",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Option<Vec<serde_json::Value>>>,
    /// The URL of the privacy policy for the campaign.
    #[serde(
        rename = "privacy_policy_url",
        deserialize_with = "Option::deserialize"
    )]
    pub privacy_policy_url: Option<String>,
    /// The URL of the terms and conditions for the campaign.
    #[serde(
        rename = "terms_and_conditions_url",
        deserialize_with = "Option::deserialize"
    )]
    pub terms_and_conditions_url: Option<String>,
}

impl MessagingV1ServiceUsAppToPersonV2 {
    pub fn new(
        privacy_policy_url: Option<String>,
        terms_and_conditions_url: Option<String>,
    ) -> MessagingV1ServiceUsAppToPersonV2 {
        MessagingV1ServiceUsAppToPersonV2 {
            sid: None,
            account_sid: None,
            brand_registration_sid: None,
            messaging_service_sid: None,
            description: None,
            message_samples: None,
            us_app_to_person_usecase: None,
            has_embedded_links: None,
            has_embedded_phone: None,
            subscriber_opt_in: None,
            age_gated: None,
            direct_lending: None,
            campaign_status: None,
            campaign_id: None,
            is_externally_registered: None,
            rate_limits: None,
            message_flow: None,
            opt_in_message: None,
            opt_out_message: None,
            help_message: None,
            opt_in_keywords: None,
            opt_out_keywords: None,
            help_keywords: None,
            date_created: None,
            date_updated: None,
            url: None,
            mock: None,
            errors: None,
            privacy_policy_url,
            terms_and_conditions_url,
        }
    }
}
