// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceUsAppToPersonUsecase {
    /// Human readable name, code, description and post_approval_required (indicates whether or not post approval is required for this Use Case) of A2P Campaign Use Cases.
    #[serde(
        rename = "us_app_to_person_usecases",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub us_app_to_person_usecases: Option<Option<Vec<serde_json::Value>>>,
}

impl MessagingV1ServiceUsAppToPersonUsecase {
    pub fn new() -> MessagingV1ServiceUsAppToPersonUsecase {
        MessagingV1ServiceUsAppToPersonUsecase {
            us_app_to_person_usecases: None,
        }
    }
}
