// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceServiceForNumber {
    /// The SID to identify the number resource.
    #[serde(
        rename = "number_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_sid: Option<Option<String>>,
    /// The SID of the messaging service that the phone number is in.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The string that you assigned to describe the messaging service resource.
    #[serde(
        rename = "friendly_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub friendly_name: Option<Option<String>>,
    /// The absolute URL of the Service resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1ServiceServiceForNumber {
    pub fn new() -> MessagingV1ServiceServiceForNumber {
        MessagingV1ServiceServiceForNumber {
            number_sid: None,
            sid: None,
            friendly_name: None,
            url: None,
        }
    }
}
