// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1Deactivation {
    /// Returns an authenticated url that redirects to a file containing the deactivated numbers for the requested day. This url is valid for up to two minutes.
    #[serde(
        rename = "redirect_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redirect_to: Option<Option<String>>,
}

impl MessagingV1Deactivation {
    pub fn new() -> MessagingV1Deactivation {
        MessagingV1Deactivation { redirect_to: None }
    }
}
