// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1TollfreeVerification {
    /// The unique string to identify Tollfree Verification.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Tollfree Verification resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// Customer's Profile Bundle BundleSid.
    #[serde(
        rename = "customer_profile_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_profile_sid: Option<Option<String>>,
    /// Tollfree TrustProduct Bundle BundleSid.
    #[serde(
        rename = "trust_product_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trust_product_sid: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The SID of the Regulated Item.
    #[serde(
        rename = "regulated_item_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub regulated_item_sid: Option<Option<String>>,
    /// The name of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<Option<String>>,
    /// The address of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_street_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_street_address: Option<Option<String>>,
    /// The address of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_street_address2",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_street_address2: Option<Option<String>>,
    /// The city of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_city",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_city: Option<Option<String>>,
    /// The state/province/region of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_state_province_region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_state_province_region: Option<Option<String>>,
    /// The postal code of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_postal_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_postal_code: Option<Option<String>>,
    /// The country of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_country",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_country: Option<Option<String>>,
    /// The website of the business or organization using the Tollfree number.
    #[serde(
        rename = "business_website",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_website: Option<Option<String>>,
    /// The first name of the contact for the business or organization using the Tollfree number.
    #[serde(
        rename = "business_contact_first_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_contact_first_name: Option<Option<String>>,
    /// The last name of the contact for the business or organization using the Tollfree number.
    #[serde(
        rename = "business_contact_last_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_contact_last_name: Option<Option<String>>,
    /// The email address of the contact for the business or organization using the Tollfree number.
    #[serde(
        rename = "business_contact_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_contact_email: Option<Option<String>>,
    /// The E.164 formatted phone number of the contact for the business or organization using the Tollfree number.
    #[serde(
        rename = "business_contact_phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_contact_phone: Option<Option<String>>,
    /// The email address to receive the notification about the verification result. .
    #[serde(
        rename = "notification_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_email: Option<Option<String>>,
    /// The category of the use case for the Tollfree Number. List as many as are applicable.
    #[serde(
        rename = "use_case_categories",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_case_categories: Option<Option<Vec<UseCaseCategories>>>,
    /// Use this to further explain how messaging is used by the business or organization.
    #[serde(
        rename = "use_case_summary",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_case_summary: Option<Option<String>>,
    /// An example of message content, i.e. a sample message.
    #[serde(
        rename = "production_message_sample",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub production_message_sample: Option<Option<String>>,
    /// Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL.
    #[serde(
        rename = "opt_in_image_urls",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_in_image_urls: Option<Option<Vec<String>>>,
    #[serde(rename = "opt_in_type", skip_serializing_if = "Option::is_none")]
    pub opt_in_type: Option<models::TollfreeVerificationEnumOptInType>,
    /// Estimate monthly volume of messages from the Tollfree Number.
    #[serde(
        rename = "message_volume",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_volume: Option<Option<String>>,
    /// Additional information to be provided for verification.
    #[serde(
        rename = "additional_information",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_information: Option<Option<String>>,
    /// The SID of the Phone Number associated with the Tollfree Verification.
    #[serde(
        rename = "tollfree_phone_number_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tollfree_phone_number_sid: Option<Option<String>>,
    /// The E.164 formatted toll-free phone number associated with the verification.
    #[serde(
        rename = "tollfree_phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tollfree_phone_number: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::TollfreeVerificationEnumStatus>,
    /// The absolute URL of the Tollfree Verification resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// The rejection reason given when a Tollfree Verification has been rejected.
    #[serde(
        rename = "rejection_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rejection_reason: Option<Option<String>>,
    /// The error code given when a Tollfree Verification has been rejected.
    #[serde(
        rename = "error_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_code: Option<Option<i32>>,
    /// The date and time when the ability to edit a rejected verification expires.
    #[serde(
        rename = "edit_expiration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub edit_expiration: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// If a rejected verification is allowed to be edited/resubmitted. Some rejection reasons allow editing and some do not.
    #[serde(
        rename = "edit_allowed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub edit_allowed: Option<Option<bool>>,
    /// A legally recognized business registration number
    #[serde(
        rename = "business_registration_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_registration_number: Option<Option<String>>,
    #[serde(
        rename = "business_registration_authority",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_registration_authority:
        Option<Option<models::TollfreeVerificationEnumBusinessRegistrationAuthority>>,
    /// Country business is registered in
    #[serde(
        rename = "business_registration_country",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_registration_country: Option<Option<String>>,
    #[serde(
        rename = "business_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_type: Option<Option<models::TollfreeVerificationEnumBusinessType>>,
    /// The E.164 formatted number associated with the business.
    #[serde(
        rename = "business_registration_phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_registration_phone_number: Option<Option<String>>,
    /// Trade name, sub entity, or downstream business name of business being submitted for verification
    #[serde(
        rename = "doing_business_as",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub doing_business_as: Option<Option<String>>,
    /// The confirmation message sent to users when they opt in to receive messages.
    #[serde(
        rename = "opt_in_confirmation_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_in_confirmation_message: Option<Option<String>>,
    /// A sample help message provided to users.
    #[serde(
        rename = "help_message_sample",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub help_message_sample: Option<Option<String>>,
    /// The URL to the privacy policy for the business or organization.
    #[serde(
        rename = "privacy_policy_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub privacy_policy_url: Option<Option<String>>,
    /// The URL of the terms and conditions for the business or organization.
    #[serde(
        rename = "terms_and_conditions_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub terms_and_conditions_url: Option<Option<String>>,
    /// Indicates if the content is age gated.
    #[serde(
        rename = "age_gated_content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub age_gated_content: Option<Option<bool>>,
    /// List of keywords that users can send to opt in or out of messages.
    #[serde(
        rename = "opt_in_keywords",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub opt_in_keywords: Option<Option<Vec<String>>>,
    /// A list of rejection reasons and codes describing why a Tollfree Verification has been rejected.
    #[serde(
        rename = "rejection_reasons",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rejection_reasons: Option<Option<Vec<serde_json::Value>>>,
    /// The URLs of the documents associated with the Tollfree Verification resource.
    #[serde(
        rename = "resource_links",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_links: Option<Option<serde_json::Value>>,
    /// An optional external reference ID supplied by customer and echoed back on status retrieval.
    #[serde(
        rename = "external_reference_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_reference_id: Option<Option<String>>,
    #[serde(
        rename = "vetting_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_id: Option<Option<String>>,
    #[serde(
        rename = "vetting_provider",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_provider: Option<Option<models::TollfreeVerificationEnumVettingProvider>>,
    #[serde(
        rename = "vetting_id_expiration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_id_expiration: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl MessagingV1TollfreeVerification {
    pub fn new() -> MessagingV1TollfreeVerification {
        MessagingV1TollfreeVerification {
            sid: None,
            account_sid: None,
            customer_profile_sid: None,
            trust_product_sid: None,
            date_created: None,
            date_updated: None,
            regulated_item_sid: None,
            business_name: None,
            business_street_address: None,
            business_street_address2: None,
            business_city: None,
            business_state_province_region: None,
            business_postal_code: None,
            business_country: None,
            business_website: None,
            business_contact_first_name: None,
            business_contact_last_name: None,
            business_contact_email: None,
            business_contact_phone: None,
            notification_email: None,
            use_case_categories: None,
            use_case_summary: None,
            production_message_sample: None,
            opt_in_image_urls: None,
            opt_in_type: None,
            message_volume: None,
            additional_information: None,
            tollfree_phone_number_sid: None,
            tollfree_phone_number: None,
            status: None,
            url: None,
            rejection_reason: None,
            error_code: None,
            edit_expiration: None,
            edit_allowed: None,
            business_registration_number: None,
            business_registration_authority: None,
            business_registration_country: None,
            business_type: None,
            business_registration_phone_number: None,
            doing_business_as: None,
            opt_in_confirmation_message: None,
            help_message_sample: None,
            privacy_policy_url: None,
            terms_and_conditions_url: None,
            age_gated_content: None,
            opt_in_keywords: None,
            rejection_reasons: None,
            resource_links: None,
            external_reference_id: None,
            vetting_id: None,
            vetting_provider: None,
            vetting_id_expiration: None,
        }
    }
}
/// The category of the use case for the Tollfree Number. List as many as are applicable.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum UseCaseCategories {
    TwoFactorAuthentication,
    AccountNotifications,
    CustomerCare,
    CharityNonprofit,
    DeliveryNotifications,
    FraudAlertMessaging,
    Events,
    HigherEducation,
    K12,
    Marketing,
    PollingAndVotingNonPolitical,
    PoliticalElectionCampaigns,
    PublicServiceAnnouncement,
    SecurityAlert,
    Unknown(String),
}

impl UseCaseCategories {
    pub fn as_str(&self) -> &str {
        match self {
            Self::TwoFactorAuthentication => "TWO_FACTOR_AUTHENTICATION",
            Self::AccountNotifications => "ACCOUNT_NOTIFICATIONS",
            Self::CustomerCare => "CUSTOMER_CARE",
            Self::CharityNonprofit => "CHARITY_NONPROFIT",
            Self::DeliveryNotifications => "DELIVERY_NOTIFICATIONS",
            Self::FraudAlertMessaging => "FRAUD_ALERT_MESSAGING",
            Self::Events => "EVENTS",
            Self::HigherEducation => "HIGHER_EDUCATION",
            Self::K12 => "K12",
            Self::Marketing => "MARKETING",
            Self::PollingAndVotingNonPolitical => "POLLING_AND_VOTING_NON_POLITICAL",
            Self::PoliticalElectionCampaigns => "POLITICAL_ELECTION_CAMPAIGNS",
            Self::PublicServiceAnnouncement => "PUBLIC_SERVICE_ANNOUNCEMENT",
            Self::SecurityAlert => "SECURITY_ALERT",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for UseCaseCategories {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for UseCaseCategories {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "TWO_FACTOR_AUTHENTICATION" => Self::TwoFactorAuthentication,
            "ACCOUNT_NOTIFICATIONS" => Self::AccountNotifications,
            "CUSTOMER_CARE" => Self::CustomerCare,
            "CHARITY_NONPROFIT" => Self::CharityNonprofit,
            "DELIVERY_NOTIFICATIONS" => Self::DeliveryNotifications,
            "FRAUD_ALERT_MESSAGING" => Self::FraudAlertMessaging,
            "EVENTS" => Self::Events,
            "HIGHER_EDUCATION" => Self::HigherEducation,
            "K12" => Self::K12,
            "MARKETING" => Self::Marketing,
            "POLLING_AND_VOTING_NON_POLITICAL" => Self::PollingAndVotingNonPolitical,
            "POLITICAL_ELECTION_CAMPAIGNS" => Self::PoliticalElectionCampaigns,
            "PUBLIC_SERVICE_ANNOUNCEMENT" => Self::PublicServiceAnnouncement,
            "SECURITY_ALERT" => Self::SecurityAlert,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for UseCaseCategories {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for UseCaseCategories {
    fn default() -> UseCaseCategories {
        Self::TwoFactorAuthentication
    }
}
