// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1DomainCertV4 {
    /// The unique string that we created to identify the Domain resource.
    #[serde(
        rename = "domain_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_sid: Option<Option<String>>,
    /// Date that this Domain was last updated.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Date that the private certificate associated with this domain expires. You will need to update the certificate before that date to ensure your shortened links will continue to work.
    #[serde(
        rename = "date_expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_expires: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Date that this Domain was registered to the Twilio platform to create a new Domain object.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Full url path for this domain.
    #[serde(
        rename = "domain_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_name: Option<Option<String>>,
    /// The unique string that we created to identify this Certificate resource.
    #[serde(
        rename = "certificate_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_sid: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// Optional JSON field describing the status and upload date of a new certificate in the process of validation
    #[serde(
        rename = "cert_in_validation",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cert_in_validation: Option<Option<serde_json::Value>>,
}

impl MessagingV1DomainCertV4 {
    pub fn new() -> MessagingV1DomainCertV4 {
        MessagingV1DomainCertV4 {
            domain_sid: None,
            date_updated: None,
            date_expires: None,
            date_created: None,
            domain_name: None,
            certificate_sid: None,
            url: None,
            cert_in_validation: None,
        }
    }
}
