// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceShortCode {
    /// The unique string that we created to identify the ShortCode resource.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with.
    #[serde(
        rename = "service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_sid: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The [E.164](https://www.twilio.com/docs/glossary/what-e164) format of the short code.
    #[serde(
        rename = "short_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub short_code: Option<Option<String>>,
    /// The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number.
    #[serde(
        rename = "country_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country_code: Option<Option<String>>,
    /// An array of values that describe whether the number can receive calls or messages. Can be: `SMS` and `MMS`.
    #[serde(
        rename = "capabilities",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub capabilities: Option<Option<Vec<String>>>,
    /// The absolute URL of the ShortCode resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1ServiceShortCode {
    pub fn new() -> MessagingV1ServiceShortCode {
        MessagingV1ServiceShortCode {
            sid: None,
            account_sid: None,
            service_sid: None,
            date_created: None,
            date_updated: None,
            short_code: None,
            country_code: None,
            capabilities: None,
            url: None,
        }
    }
}
