// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1LinkshorteningMessagingServiceDomainAssociation {
    /// The unique string that we created to identify the Domain resource.
    #[serde(
        rename = "domain_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_sid: Option<Option<String>>,
    /// The unique string that identifies the messaging service
    #[serde(
        rename = "messaging_service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub messaging_service_sid: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1LinkshorteningMessagingServiceDomainAssociation {
    pub fn new() -> MessagingV1LinkshorteningMessagingServiceDomainAssociation {
        MessagingV1LinkshorteningMessagingServiceDomainAssociation {
            domain_sid: None,
            messaging_service_sid: None,
            url: None,
        }
    }
}
