// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1Usecase {
    /// Human readable use case details (usecase, description and purpose) of Messaging Service Use Cases.
    #[serde(
        rename = "usecases",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub usecases: Option<Option<Vec<serde_json::Value>>>,
}

impl MessagingV1Usecase {
    pub fn new() -> MessagingV1Usecase {
        MessagingV1Usecase { usecases: None }
    }
}
