// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1DomainConfigMessagingService {
    /// The unique string that we created to identify the Domain resource.
    #[serde(
        rename = "domain_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_sid: Option<Option<String>>,
    /// The unique string that we created to identify the Domain config (prefix ZK).
    #[serde(
        rename = "config_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_sid: Option<Option<String>>,
    /// The unique string that identifies the messaging service
    #[serde(
        rename = "messaging_service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub messaging_service_sid: Option<Option<String>>,
    /// Any requests we receive to this domain that do not match an existing shortened message will be redirected to the fallback url. These will likely be either expired messages, random misdirected traffic, or intentional scraping.
    #[serde(
        rename = "fallback_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback_url: Option<Option<String>>,
    /// URL to receive click events to your webhook whenever the recipients click on the shortened links.
    #[serde(
        rename = "callback_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub callback_url: Option<Option<String>>,
    /// Boolean field to set customer delivery preference when there is a failure in linkShortening service
    #[serde(
        rename = "continue_on_failure",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub continue_on_failure: Option<Option<bool>>,
    /// Date this Domain Config was created.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Date that this Domain Config was last updated.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1DomainConfigMessagingService {
    pub fn new() -> MessagingV1DomainConfigMessagingService {
        MessagingV1DomainConfigMessagingService {
            domain_sid: None,
            config_sid: None,
            messaging_service_sid: None,
            fallback_url: None,
            callback_url: None,
            continue_on_failure: None,
            date_created: None,
            date_updated: None,
            url: None,
        }
    }
}
