// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1ServiceChannelSender {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ChannelSender resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The SID of the [Service](https://www.twilio.com/docs/messaging/services) the resource is associated with.
    #[serde(
        rename = "messaging_service_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub messaging_service_sid: Option<Option<String>>,
    /// The unique string that we created to identify the ChannelSender resource.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The unique string that identifies the sender e.g whatsapp:+123456XXXX.
    #[serde(
        rename = "sender",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sender: Option<Option<String>>,
    /// A string value that identifies the sender type e.g WhatsApp, Messenger.
    #[serde(
        rename = "sender_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sender_type: Option<Option<String>>,
    /// The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number.
    #[serde(
        rename = "country_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country_code: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The absolute URL of the ChannelSender resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1ServiceChannelSender {
    pub fn new() -> MessagingV1ServiceChannelSender {
        MessagingV1ServiceChannelSender {
            account_sid: None,
            messaging_service_sid: None,
            sid: None,
            sender: None,
            sender_type: None,
            country_code: None,
            date_created: None,
            date_updated: None,
            url: None,
        }
    }
}
