// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1BrandRegistrationsBrandVetting {
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the vetting record.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The unique string to identify Brand Registration.
    #[serde(
        rename = "brand_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_sid: Option<Option<String>>,
    /// The Twilio SID of the third-party vetting record.
    #[serde(
        rename = "brand_vetting_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_vetting_sid: Option<Option<String>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The unique identifier of the vetting from the third-party provider.
    #[serde(
        rename = "vetting_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_id: Option<Option<String>>,
    /// The type of vetting that has been conducted. One of “STANDARD” (Aegis) or “POLITICAL” (Campaign Verify).
    #[serde(
        rename = "vetting_class",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_class: Option<Option<String>>,
    /// The status of the import vetting attempt. One of “PENDING,” “SUCCESS,” or “FAILED”.
    #[serde(
        rename = "vetting_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vetting_status: Option<Option<String>>,
    #[serde(rename = "vetting_provider", skip_serializing_if = "Option::is_none")]
    pub vetting_provider: Option<models::BrandVettingEnumVettingProvider>,
    /// The absolute URL of the Brand Vetting resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl MessagingV1BrandRegistrationsBrandVetting {
    pub fn new() -> MessagingV1BrandRegistrationsBrandVetting {
        MessagingV1BrandRegistrationsBrandVetting {
            account_sid: None,
            brand_sid: None,
            brand_vetting_sid: None,
            date_updated: None,
            date_created: None,
            vetting_id: None,
            vetting_class: None,
            vetting_status: None,
            vetting_provider: None,
            url: None,
        }
    }
}
