// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessagingV1ServiceUsAppToPersonResponse {
    MessagingV1ServiceUsAppToPerson(Box<models::MessagingV1ServiceUsAppToPerson>),
    MessagingV1ServiceUsAppToPersonV2(Box<models::MessagingV1ServiceUsAppToPersonV2>),
}

impl Default for MessagingV1ServiceUsAppToPersonResponse {
    fn default() -> Self {
        Self::MessagingV1ServiceUsAppToPerson(Default::default())
    }
}
