// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1Service {
    /// The unique string that we created to identify the Service resource.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// The string that you assigned to describe the resource.
    #[serde(
        rename = "friendly_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub friendly_name: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
    #[serde(
        rename = "inbound_request_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_request_url: Option<Option<String>>,
    /// The HTTP method we use to call `inbound_request_url`. Can be `GET` or `POST`.
    #[serde(
        rename = "inbound_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inbound_method: Option<Option<InboundMethod>>,
    /// The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
    #[serde(
        rename = "fallback_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback_url: Option<Option<String>>,
    /// The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
    #[serde(
        rename = "fallback_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback_method: Option<Option<FallbackMethod>>,
    /// The URL we call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
    #[serde(
        rename = "status_callback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_callback: Option<Option<String>>,
    /// Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance.
    #[serde(
        rename = "sticky_sender",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sticky_sender: Option<Option<bool>>,
    /// Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance.
    #[serde(
        rename = "mms_converter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mms_converter: Option<Option<bool>>,
    /// Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance.
    #[serde(
        rename = "smart_encoding",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub smart_encoding: Option<Option<bool>>,
    #[serde(
        rename = "scan_message_content",
        skip_serializing_if = "Option::is_none"
    )]
    pub scan_message_content: Option<models::ServiceEnumScanMessageContent>,
    /// [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures.
    #[serde(
        rename = "fallback_to_long_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fallback_to_long_code: Option<Option<bool>>,
    /// Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance.
    #[serde(
        rename = "area_code_geomatch",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub area_code_geomatch: Option<Option<bool>>,
    /// Reserved.
    #[serde(
        rename = "synchronous_validation",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub synchronous_validation: Option<Option<bool>>,
    /// How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `36,000`. Default value is `36,000`.
    #[serde(rename = "validity_period", skip_serializing_if = "Option::is_none")]
    pub validity_period: Option<i32>,
    /// The absolute URL of the Service resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// The absolute URLs of related resources.
    #[serde(
        rename = "links",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub links: Option<Option<serde_json::Value>>,
    /// A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`.
    #[serde(
        rename = "usecase",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub usecase: Option<Option<String>>,
    /// Whether US A2P campaign is registered for this Service.
    #[serde(
        rename = "us_app_to_person_registered",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub us_app_to_person_registered: Option<Option<bool>>,
    /// A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service.
    #[serde(
        rename = "use_inbound_webhook_on_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_inbound_webhook_on_number: Option<Option<bool>>,
}

impl MessagingV1Service {
    pub fn new() -> MessagingV1Service {
        MessagingV1Service {
            sid: None,
            account_sid: None,
            friendly_name: None,
            date_created: None,
            date_updated: None,
            inbound_request_url: None,
            inbound_method: None,
            fallback_url: None,
            fallback_method: None,
            status_callback: None,
            sticky_sender: None,
            mms_converter: None,
            smart_encoding: None,
            scan_message_content: None,
            fallback_to_long_code: None,
            area_code_geomatch: None,
            synchronous_validation: None,
            validity_period: None,
            url: None,
            links: None,
            usecase: None,
            us_app_to_person_registered: None,
            use_inbound_webhook_on_number: None,
        }
    }
}
/// The HTTP method we use to call `inbound_request_url`. Can be `GET` or `POST`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum InboundMethod {
    Get,
    Post,
    Unknown(String),
}

impl InboundMethod {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for InboundMethod {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for InboundMethod {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "GET" => Self::Get,
            "POST" => Self::Post,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for InboundMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for InboundMethod {
    fn default() -> InboundMethod {
        Self::Get
    }
}
/// The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum FallbackMethod {
    Get,
    Post,
    Unknown(String),
}

impl FallbackMethod {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for FallbackMethod {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for FallbackMethod {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "GET" => Self::Get,
            "POST" => Self::Post,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for FallbackMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for FallbackMethod {
    fn default() -> FallbackMethod {
        Self::Get
    }
}
