// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1BrandRegistrations {
    /// The unique string to identify Brand Registration.
    #[serde(
        rename = "sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sid: Option<Option<String>>,
    /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource.
    #[serde(
        rename = "account_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_sid: Option<Option<String>>,
    /// A2P Messaging Profile Bundle BundleSid.
    #[serde(
        rename = "customer_profile_bundle_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_profile_bundle_sid: Option<Option<String>>,
    /// A2P Messaging Profile Bundle BundleSid.
    #[serde(
        rename = "a2p_profile_bundle_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub a2p_profile_bundle_sid: Option<Option<String>>,
    /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Type of brand. One of: \"STANDARD\", \"SOLE_PROPRIETOR\". SOLE_PROPRIETOR is for the low volume, SOLE_PROPRIETOR campaign use case. There can only be one SOLE_PROPRIETOR campaign created per SOLE_PROPRIETOR brand. STANDARD is for all other campaign use cases. Multiple campaign use cases can be created per STANDARD brand.
    #[serde(
        rename = "brand_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_type: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::BrandRegistrationsEnumStatus>,
    /// Campaign Registry (TCR) Brand ID. Assigned only after successful brand registration.
    #[serde(
        rename = "tcr_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tcr_id: Option<Option<String>>,
    /// DEPRECATED. A reason why brand registration has failed. Only applicable when status is FAILED.
    #[serde(
        rename = "failure_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub failure_reason: Option<Option<String>>,
    /// A list of errors that occurred during the brand registration process.
    #[serde(
        rename = "errors",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Option<Vec<serde_json::Value>>>,
    /// The absolute URL of the Brand Registration resource.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// The secondary vetting score if it was done. Otherwise, it will be the brand score if it's returned from TCR. It may be null if no score is available.
    #[serde(
        rename = "brand_score",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_score: Option<Option<i32>>,
    /// DEPRECATED. Feedback on how to improve brand score
    #[serde(
        rename = "brand_feedback",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub brand_feedback: Option<Option<Vec<models::BrandRegistrationsEnumBrandFeedback>>>,
    #[serde(rename = "identity_status", skip_serializing_if = "Option::is_none")]
    pub identity_status: Option<models::BrandRegistrationsEnumIdentityStatus>,
    /// Publicly traded company identified in the Russell 3000 Index
    #[serde(
        rename = "russell_3000",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub russell_3000: Option<Option<bool>>,
    /// Identified as a government entity
    #[serde(
        rename = "government_entity",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub government_entity: Option<Option<bool>>,
    /// Nonprofit organization tax-exempt status per section 501 of the U.S. tax code.
    #[serde(
        rename = "tax_exempt_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_exempt_status: Option<Option<String>>,
    /// A flag to disable automatic secondary vetting for brands which it would otherwise be done.
    #[serde(
        rename = "skip_automatic_sec_vet",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub skip_automatic_sec_vet: Option<Option<bool>>,
    /// A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided.
    #[serde(
        rename = "mock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mock: Option<Option<bool>>,
    #[serde(
        rename = "links",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub links: Option<Option<serde_json::Value>>,
}

impl MessagingV1BrandRegistrations {
    pub fn new() -> MessagingV1BrandRegistrations {
        MessagingV1BrandRegistrations {
            sid: None,
            account_sid: None,
            customer_profile_bundle_sid: None,
            a2p_profile_bundle_sid: None,
            date_created: None,
            date_updated: None,
            brand_type: None,
            status: None,
            tcr_id: None,
            failure_reason: None,
            errors: None,
            url: None,
            brand_score: None,
            brand_feedback: None,
            identity_status: None,
            russell_3000: None,
            government_entity: None,
            tax_exempt_status: None,
            skip_automatic_sec_vet: None,
            mock: None,
            links: None,
        }
    }
}
