// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingV1RequestManagedCert {
    /// The unique string that we created to identify the Domain resource.
    #[serde(
        rename = "domain_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_sid: Option<Option<String>>,
    /// Date that this Domain was last updated.
    #[serde(
        rename = "date_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_updated: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Date that this Domain was registered to the Twilio platform to create a new Domain object.
    #[serde(
        rename = "date_created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Date that the private certificate associated with this domain expires. This is the expiration date of your existing cert.
    #[serde(
        rename = "date_expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_expires: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Full url path for this domain.
    #[serde(
        rename = "domain_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub domain_name: Option<Option<String>>,
    /// The unique string that we created to identify this Certificate resource.
    #[serde(
        rename = "certificate_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub certificate_sid: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    /// A boolean flag indicating if the certificate is managed by Twilio.
    #[serde(
        rename = "managed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub managed: Option<Option<bool>>,
    /// A boolean flag indicating if a managed certificate needs to be fulfilled by Twilio.
    #[serde(
        rename = "requesting",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requesting: Option<Option<bool>>,
}

impl MessagingV1RequestManagedCert {
    pub fn new() -> MessagingV1RequestManagedCert {
        MessagingV1RequestManagedCert {
            domain_sid: None,
            date_updated: None,
            date_created: None,
            date_expires: None,
            domain_name: None,
            certificate_sid: None,
            url: None,
            managed: None,
            requesting: None,
        }
    }
}
