// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceEnumScanMessageContent : Reserved.
/// Reserved.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum ServiceEnumScanMessageContent {
    Inherit,
    Enable,
    Disable,

    Unknown(String),
}

impl ServiceEnumScanMessageContent {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Inherit => "inherit",
            Self::Enable => "enable",
            Self::Disable => "disable",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ServiceEnumScanMessageContent {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ServiceEnumScanMessageContent {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "inherit" => Self::Inherit,
            "enable" => Self::Enable,
            "disable" => Self::Disable,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for ServiceEnumScanMessageContent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for ServiceEnumScanMessageContent {
    fn default() -> ServiceEnumScanMessageContent {
        Self::Inherit
    }
}
