// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// TollfreeVerificationEnumStatus : The compliance status of the Tollfree Verification record.
/// The compliance status of the Tollfree Verification record.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum TollfreeVerificationEnumStatus {
    PendingReview,
    InReview,
    TwilioApproved,
    TwilioRejected,

    Unknown(String),
}

impl TollfreeVerificationEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PendingReview => "PENDING_REVIEW",
            Self::InReview => "IN_REVIEW",
            Self::TwilioApproved => "TWILIO_APPROVED",
            Self::TwilioRejected => "TWILIO_REJECTED",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for TollfreeVerificationEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TollfreeVerificationEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "PENDING_REVIEW" => Self::PendingReview,
            "IN_REVIEW" => Self::InReview,
            "TWILIO_APPROVED" => Self::TwilioApproved,
            "TWILIO_REJECTED" => Self::TwilioRejected,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for TollfreeVerificationEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for TollfreeVerificationEnumStatus {
    fn default() -> TollfreeVerificationEnumStatus {
        Self::PendingReview
    }
}
