// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// TollfreeVerificationEnumOptInType : Describe how a user opts-in to text messages.
/// Describe how a user opts-in to text messages.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum TollfreeVerificationEnumOptInType {
    Verbal,
    WebForm,
    PaperForm,
    ViaText,
    MobileQrCode,
    Import,
    ImportPleaseReplace,

    Unknown(String),
}

impl TollfreeVerificationEnumOptInType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Verbal => "VERBAL",
            Self::WebForm => "WEB_FORM",
            Self::PaperForm => "PAPER_FORM",
            Self::ViaText => "VIA_TEXT",
            Self::MobileQrCode => "MOBILE_QR_CODE",
            Self::Import => "IMPORT",
            Self::ImportPleaseReplace => "IMPORT_PLEASE_REPLACE",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for TollfreeVerificationEnumOptInType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TollfreeVerificationEnumOptInType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "VERBAL" => Self::Verbal,
            "WEB_FORM" => Self::WebForm,
            "PAPER_FORM" => Self::PaperForm,
            "VIA_TEXT" => Self::ViaText,
            "MOBILE_QR_CODE" => Self::MobileQrCode,
            "IMPORT" => Self::Import,
            "IMPORT_PLEASE_REPLACE" => Self::ImportPleaseReplace,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for TollfreeVerificationEnumOptInType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for TollfreeVerificationEnumOptInType {
    fn default() -> TollfreeVerificationEnumOptInType {
        Self::Verbal
    }
}
