// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// TollfreeVerificationEnumVettingProvider : The third-party political vetting provider.
/// The third-party political vetting provider.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum TollfreeVerificationEnumVettingProvider {
    CampaignVerify,

    Unknown(String),
}

impl TollfreeVerificationEnumVettingProvider {
    pub fn as_str(&self) -> &str {
        match self {
            Self::CampaignVerify => "CAMPAIGN_VERIFY",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for TollfreeVerificationEnumVettingProvider {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TollfreeVerificationEnumVettingProvider {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "CAMPAIGN_VERIFY" => Self::CampaignVerify,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for TollfreeVerificationEnumVettingProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for TollfreeVerificationEnumVettingProvider {
    fn default() -> TollfreeVerificationEnumVettingProvider {
        Self::CampaignVerify
    }
}
