// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// TollfreeVerificationEnumBusinessRegistrationAuthority : The organizational authority for business registrations. Required for all business types except SOLE_PROPRIETOR.
/// The organizational authority for business registrations. Required for all business types except SOLE_PROPRIETOR.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum TollfreeVerificationEnumBusinessRegistrationAuthority {
    Ein,
    Cbn,
    Crn,
    ProvincialNumber,
    Vat,
    Acn,
    Abn,
    Brn,
    Siren,
    Siret,
    Nzbn,
    UstIdNr,
    Cif,
    Nif,
    Cnpj,
    Uid,
    Neq,
    Other,

    Unknown(String),
}

impl TollfreeVerificationEnumBusinessRegistrationAuthority {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Ein => "EIN",
            Self::Cbn => "CBN",
            Self::Crn => "CRN",
            Self::ProvincialNumber => "PROVINCIAL_NUMBER",
            Self::Vat => "VAT",
            Self::Acn => "ACN",
            Self::Abn => "ABN",
            Self::Brn => "BRN",
            Self::Siren => "SIREN",
            Self::Siret => "SIRET",
            Self::Nzbn => "NZBN",
            Self::UstIdNr => "USt-IdNr",
            Self::Cif => "CIF",
            Self::Nif => "NIF",
            Self::Cnpj => "CNPJ",
            Self::Uid => "UID",
            Self::Neq => "NEQ",
            Self::Other => "OTHER",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for TollfreeVerificationEnumBusinessRegistrationAuthority {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TollfreeVerificationEnumBusinessRegistrationAuthority {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "EIN" => Self::Ein,
            "CBN" => Self::Cbn,
            "CRN" => Self::Crn,
            "PROVINCIAL_NUMBER" => Self::ProvincialNumber,
            "VAT" => Self::Vat,
            "ACN" => Self::Acn,
            "ABN" => Self::Abn,
            "BRN" => Self::Brn,
            "SIREN" => Self::Siren,
            "SIRET" => Self::Siret,
            "NZBN" => Self::Nzbn,
            "USt-IdNr" => Self::UstIdNr,
            "CIF" => Self::Cif,
            "NIF" => Self::Nif,
            "CNPJ" => Self::Cnpj,
            "UID" => Self::Uid,
            "NEQ" => Self::Neq,
            "OTHER" => Self::Other,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for TollfreeVerificationEnumBusinessRegistrationAuthority {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for TollfreeVerificationEnumBusinessRegistrationAuthority {
    fn default() -> TollfreeVerificationEnumBusinessRegistrationAuthority {
        Self::Ein
    }
}
