// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
#![allow(warnings)]

extern crate reqwest;
extern crate serde;
extern crate serde_json;
extern crate serde_repr;
extern crate url;

pub use dialkit_core as core;
pub mod apis;
pub mod models;
pub mod pagination;
