// @generated by codegen/contracts/generate_pagination.py.
// DO NOT EDIT: update pinned contracts and rerun regeneration.

use crate::{apis::configuration::Configuration, models};
use dialkit_core::{
    error::Error,
    pagination::{Page, Pager},
    request::RequestSpec,
    retry::OperationSafety,
};
use serde::de::DeserializeOwned;

pub trait PageResponse: DeserializeOwned + Send + 'static {
    type Item: Send + Unpin + 'static;
    fn into_page(self) -> Page<Self::Item>;
}

/// Continues from a generated one-page response using opaque Twilio links.
/// The shared transport rejects malformed and cross-origin continuations and
/// `Pager` rejects repeated continuation links.
pub fn follow<P>(configuration: Configuration, first: P) -> Pager<P::Item>
where
    P: PageResponse,
{
    let mut first = Some(first);
    Pager::new(move |continuation| {
        let configuration = configuration.clone();
        let initial = first.take();
        Box::pin(async move {
            let response = match (initial, continuation) {
                (Some(response), None) => response,
                (_, Some(uri)) => {
                    let request = RequestSpec {
                        operation: "generated_list_continuation",
                        method: reqwest::Method::GET,
                        route_template: "/generated/pagination",
                        path: uri,
                        query: Vec::new(),
                        form: Vec::new(),
                        safety: OperationSafety::Read,
                    };
                    configuration.client.execute_json::<P>(&request).await?
                }
                (None, None) => {
                    return Err(Error::Validation(
                        "missing initial pagination response".into(),
                    ));
                }
            };
            Ok(response.into_page())
        })
    })
}

impl PageResponse for models::ListAlphaSenderResponse {
    type Item = models::MessagingV1ServiceAlphaSender;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.alpha_senders.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListBrandRegistrationsResponse {
    type Item = models::MessagingV1BrandRegistrations;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.data.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListBrandVettingResponse {
    type Item = models::MessagingV1BrandRegistrationsBrandVetting;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.data.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListChannelSenderResponse {
    type Item = models::MessagingV1ServiceChannelSender;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.senders.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListDestinationAlphaSenderResponse {
    type Item = models::MessagingV1ServiceDestinationAlphaSender;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.alpha_senders.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListPhoneNumberResponse {
    type Item = models::MessagingV1ServicePhoneNumber;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.phone_numbers.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListServiceResponse {
    type Item = models::MessagingV1Service;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.services.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListShortCodeResponse {
    type Item = models::MessagingV1ServiceShortCode;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.short_codes.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListTollfreeVerificationResponse {
    type Item = models::MessagingV1TollfreeVerification;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.verifications.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
impl PageResponse for models::ListUsAppToPersonResponse {
    type Item = models::MessagingV1ServiceUsAppToPersonResponse;

    fn into_page(self) -> Page<Self::Item> {
        Page {
            items: self.compliance.unwrap_or_default(),
            next_page_uri: self.meta.and_then(|meta| meta.next_page_url.flatten()),
        }
    }
}
