// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_linkshortening_messaging_service`]
#[derive(Clone, Debug)]
pub struct CreateLinkshorteningMessagingServiceParams {
    /// The domain SID to associate with a messaging service. With URL shortening enabled, links in messages sent with the associated messaging service will be shortened to the provided domain
    pub domain_sid: String,
    /// A messaging service SID to associate with a domain. With URL shortening enabled, links in messages sent with the provided messaging service will be shortened to the associated domain
    pub messaging_service_sid: String,
}

/// struct for passing parameters to the method [`delete_linkshortening_messaging_service`]
#[derive(Clone, Debug)]
pub struct DeleteLinkshorteningMessagingServiceParams {
    /// The domain SID to dissociate from a messaging service. With URL shortening enabled, links in messages sent with the associated messaging service will be shortened to the provided domain
    pub domain_sid: String,
    /// A messaging service SID to dissociate from a domain. With URL shortening enabled, links in messages sent with the provided messaging service will be shortened to the associated domain
    pub messaging_service_sid: String,
}

/// struct for typed errors of method [`create_linkshortening_messaging_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateLinkshorteningMessagingServiceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_linkshortening_messaging_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteLinkshorteningMessagingServiceError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_linkshortening_messaging_service(
    configuration: &configuration::Configuration,
    params: CreateLinkshorteningMessagingServiceParams,
) -> Result<
    models::MessagingV1LinkshorteningMessagingService,
    Error<CreateLinkshorteningMessagingServiceError>,
> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid),
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1LinkshorteningMessagingService`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1LinkshorteningMessagingService`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateLinkshorteningMessagingServiceError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_linkshortening_messaging_service(
    configuration: &configuration::Configuration,
    params: DeleteLinkshorteningMessagingServiceParams,
) -> Result<(), Error<DeleteLinkshorteningMessagingServiceError>> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid),
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteLinkshorteningMessagingServiceError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
