// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_external_campaign`]
#[derive(Clone, Debug)]
pub struct CreateExternalCampaignParams {
    /// ID of the preregistered campaign.
    pub campaign_id: String,
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with.
    pub messaging_service_sid: String,
    /// Customers should use this flag during the ERC registration process to indicate to Twilio that the campaign being registered is undergoing CNP migration. It is important for the user to first trigger the CNP migration process for said campaign in their CSP portal and have Twilio accept the sharing request, before making this api call.
    pub cnp_migration: Option<bool>,
}

/// struct for typed errors of method [`create_external_campaign`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateExternalCampaignError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_external_campaign(
    configuration: &configuration::Configuration,
    params: CreateExternalCampaignParams,
) -> Result<models::MessagingV1ExternalCampaign, Error<CreateExternalCampaignError>> {
    let uri_str = format!("{}/v1/Services/PreregisteredUsa2p", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("CampaignId", params.campaign_id.to_string());
    multipart_form_params.insert(
        "MessagingServiceSid",
        params.messaging_service_sid.to_string(),
    );
    if let Some(param_value) = params.cnp_migration {
        multipart_form_params.insert("CnpMigration", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ExternalCampaign`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ExternalCampaign`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateExternalCampaignError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
