// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_us_app_to_person`]
#[derive(Clone, Debug)]
pub struct CreateUsAppToPersonParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to create the resources from.
    pub messaging_service_sid: String,
    /// A2P Brand Registration SID
    pub brand_registration_sid: String,
    /// A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters.
    pub description: String,
    /// Required for all Campaigns. Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum.
    pub message_flow: String,
    /// An array of sample message strings, min two and max five. Min length for each sample: 20 chars. Max length for each sample: 1024 chars.
    pub message_samples: Vec<String>,
    /// A2P Campaign Use Case. Examples: [ 2FA, EMERGENCY, MARKETING..]
    pub us_app_to_person_usecase: String,
    /// Indicates that this SMS campaign will send messages that contain links.
    pub has_embedded_links: bool,
    /// Indicates that this SMS campaign will send messages that contain phone numbers.
    pub has_embedded_phone: bool,
    /// The version of the Messaging API to use for this request
    pub x_twilio_api_version: Option<String>,
    /// If end users can text in a keyword to start receiving messages from this campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. This field is required if end users can text in a keyword to start receiving messages from this campaign. 20 character minimum. 320 character maximum.
    pub opt_in_message: Option<String>,
    /// Upon receiving the opt-out keywords from the end users, Twilio customers are expected to send back an auto-generated response, which must provide acknowledgment of the opt-out request and confirmation that no further messages will be sent. It is also recommended that these opt-out messages include the brand name. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
    pub opt_out_message: Option<String>,
    /// When customers receive the help keywords from their end users, Twilio customers are expected to send back an auto-generated response; this may include the brand name and additional support contact information. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum.
    pub help_message: Option<String>,
    /// If end users can text in a keyword to start receiving messages from this campaign, those keywords must be provided. This field is required if end users can text in a keyword to start receiving messages from this campaign. Values must be alphanumeric. 255 character maximum.
    pub opt_in_keywords: Option<Vec<String>>,
    /// End users should be able to text in a keyword to stop receiving messages from this campaign. Those keywords must be provided. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
    pub opt_out_keywords: Option<Vec<String>>,
    /// End users should be able to text in a keyword to receive help. Those keywords must be provided as part of the campaign registration request. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum.
    pub help_keywords: Option<Vec<String>>,
    /// A boolean that specifies whether campaign has Subscriber Optin or not.
    pub subscriber_opt_in: Option<bool>,
    /// A boolean that specifies whether campaign is age gated or not.
    pub age_gated: Option<bool>,
    /// A boolean that specifies whether campaign allows direct lending or not.
    pub direct_lending: Option<bool>,
    /// The URL of the privacy policy for the campaign.
    pub privacy_policy_url: Option<String>,
    /// The URL of the terms and conditions for the campaign.
    pub terms_and_conditions_url: Option<String>,
}

/// struct for passing parameters to the method [`delete_us_app_to_person`]
#[derive(Clone, Debug)]
pub struct DeleteUsAppToPersonParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to delete the resource from.
    pub messaging_service_sid: String,
    /// The SID of the US A2P Compliance resource to delete `QE2c6890da8086d771620e9b13fadeba0b`.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_us_app_to_person`]
#[derive(Clone, Debug)]
pub struct FetchUsAppToPersonParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from.
    pub messaging_service_sid: String,
    /// The SID of the US A2P Compliance resource to fetch `QE2c6890da8086d771620e9b13fadeba0b`.
    pub sid: String,
    /// The version of the Messaging API to use for this request
    pub x_twilio_api_version: Option<String>,
}

/// struct for passing parameters to the method [`list_us_app_to_person`]
#[derive(Clone, Debug)]
pub struct ListUsAppToPersonParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from.
    pub messaging_service_sid: String,
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
    /// The version of the Messaging API to use for this request
    pub x_twilio_api_version: Option<String>,
}

/// struct for passing parameters to the method [`update_us_app_to_person`]
#[derive(Clone, Debug)]
pub struct UpdateUsAppToPersonParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/services/api) to update the resource from.
    pub messaging_service_sid: String,
    /// The SID of the US A2P Compliance resource to update `QE2c6890da8086d771620e9b13fadeba0b`.
    pub sid: String,
    /// Indicates that this SMS campaign will send messages that contain links.
    pub has_embedded_links: bool,
    /// Indicates that this SMS campaign will send messages that contain phone numbers.
    pub has_embedded_phone: bool,
    /// An array of sample message strings, min two and max five. Min length for each sample: 20 chars. Max length for each sample: 1024 chars.
    pub message_samples: Vec<String>,
    /// Required for all Campaigns. Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum.
    pub message_flow: String,
    /// A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters.
    pub description: String,
    /// A boolean that specifies whether campaign requires age gate for federally legal content.
    pub age_gated: bool,
    /// A boolean that specifies whether campaign allows direct lending or not.
    pub direct_lending: bool,
    /// The version of the Messaging API to use for this request
    pub x_twilio_api_version: Option<String>,
    /// The URL of the privacy policy for the campaign.
    pub privacy_policy_url: Option<String>,
    /// The URL of the terms and conditions for the campaign.
    pub terms_and_conditions_url: Option<String>,
}

/// struct for typed errors of method [`create_us_app_to_person`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateUsAppToPersonError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_us_app_to_person`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteUsAppToPersonError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_us_app_to_person`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUsAppToPersonError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_us_app_to_person`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListUsAppToPersonError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_us_app_to_person`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateUsAppToPersonError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_us_app_to_person(
    configuration: &configuration::Configuration,
    params: CreateUsAppToPersonParams,
) -> Result<models::MessagingV1ServiceUsAppToPersonResponse, Error<CreateUsAppToPersonError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_twilio_api_version {
        req_builder = req_builder.header("X-Twilio-Api-Version", param_value.to_string());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert(
        "BrandRegistrationSid",
        params.brand_registration_sid.to_string(),
    );
    multipart_form_params.insert("Description", params.description.to_string());
    multipart_form_params.insert("MessageFlow", params.message_flow.to_string());
    for param_value in params.message_samples {
        multipart_form_params.insert("MessageSamples", param_value.to_string());
    }
    multipart_form_params.insert(
        "UsAppToPersonUsecase",
        params.us_app_to_person_usecase.to_string(),
    );
    multipart_form_params.insert("HasEmbeddedLinks", params.has_embedded_links.to_string());
    multipart_form_params.insert("HasEmbeddedPhone", params.has_embedded_phone.to_string());
    if let Some(param_value) = params.opt_in_message {
        multipart_form_params.insert("OptInMessage", param_value.to_string());
    }
    if let Some(param_value) = params.opt_out_message {
        multipart_form_params.insert("OptOutMessage", param_value.to_string());
    }
    if let Some(param_value) = params.help_message {
        multipart_form_params.insert("HelpMessage", param_value.to_string());
    }
    if let Some(param_values) = params.opt_in_keywords {
        for param_value in param_values {
            multipart_form_params.insert("OptInKeywords", param_value.to_string());
        }
    }
    if let Some(param_values) = params.opt_out_keywords {
        for param_value in param_values {
            multipart_form_params.insert("OptOutKeywords", param_value.to_string());
        }
    }
    if let Some(param_values) = params.help_keywords {
        for param_value in param_values {
            multipart_form_params.insert("HelpKeywords", param_value.to_string());
        }
    }
    if let Some(param_value) = params.subscriber_opt_in {
        multipart_form_params.insert("SubscriberOptIn", param_value.to_string());
    }
    if let Some(param_value) = params.age_gated {
        multipart_form_params.insert("AgeGated", param_value.to_string());
    }
    if let Some(param_value) = params.direct_lending {
        multipart_form_params.insert("DirectLending", param_value.to_string());
    }
    if let Some(param_value) = params.privacy_policy_url {
        multipart_form_params.insert("PrivacyPolicyUrl", param_value.to_string());
    }
    if let Some(param_value) = params.terms_and_conditions_url {
        multipart_form_params.insert("TermsAndConditionsUrl", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateUsAppToPersonError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_us_app_to_person(
    configuration: &configuration::Configuration,
    params: DeleteUsAppToPersonParams,
) -> Result<(), Error<DeleteUsAppToPersonError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteUsAppToPersonError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_us_app_to_person(
    configuration: &configuration::Configuration,
    params: FetchUsAppToPersonParams,
) -> Result<models::MessagingV1ServiceUsAppToPersonResponse, Error<FetchUsAppToPersonError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_twilio_api_version {
        req_builder = req_builder.header("X-Twilio-Api-Version", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUsAppToPersonError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_us_app_to_person(
    configuration: &configuration::Configuration,
    params: ListUsAppToPersonParams,
) -> Result<models::ListUsAppToPersonResponse, Error<ListUsAppToPersonError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_twilio_api_version {
        req_builder = req_builder.header("X-Twilio-Api-Version", param_value.to_string());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListUsAppToPersonResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListUsAppToPersonResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListUsAppToPersonError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn update_us_app_to_person(
    configuration: &configuration::Configuration,
    params: UpdateUsAppToPersonParams,
) -> Result<models::MessagingV1ServiceUsAppToPersonResponse, Error<UpdateUsAppToPersonError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_twilio_api_version {
        req_builder = req_builder.header("X-Twilio-Api-Version", param_value.to_string());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("HasEmbeddedLinks", params.has_embedded_links.to_string());
    multipart_form_params.insert("HasEmbeddedPhone", params.has_embedded_phone.to_string());
    for param_value in params.message_samples {
        multipart_form_params.insert("MessageSamples", param_value.to_string());
    }
    multipart_form_params.insert("MessageFlow", params.message_flow.to_string());
    multipart_form_params.insert("Description", params.description.to_string());
    multipart_form_params.insert("AgeGated", params.age_gated.to_string());
    multipart_form_params.insert("DirectLending", params.direct_lending.to_string());
    if let Some(param_value) = params.privacy_policy_url {
        multipart_form_params.insert("PrivacyPolicyUrl", param_value.to_string());
    }
    if let Some(param_value) = params.terms_and_conditions_url {
        multipart_form_params.insert("TermsAndConditionsUrl", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateUsAppToPersonError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
