// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`delete_domain_cert_v4`]
#[derive(Clone, Debug)]
pub struct DeleteDomainCertV4Params {
    /// Unique string used to identify the domain that this certificate should be associated with.
    pub domain_sid: String,
}

/// struct for passing parameters to the method [`fetch_domain_cert_v4`]
#[derive(Clone, Debug)]
pub struct FetchDomainCertV4Params {
    /// Unique string used to identify the domain that this certificate should be associated with.
    pub domain_sid: String,
}

/// struct for passing parameters to the method [`update_domain_cert_v4`]
#[derive(Clone, Debug)]
pub struct UpdateDomainCertV4Params {
    /// Unique string used to identify the domain that this certificate should be associated with.
    pub domain_sid: String,
    /// Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
    pub tls_cert: String,
}

/// struct for typed errors of method [`delete_domain_cert_v4`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDomainCertV4Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_domain_cert_v4`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchDomainCertV4Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_domain_cert_v4`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateDomainCertV4Error {
    UnknownValue(serde_json::Value),
}

///
pub async fn delete_domain_cert_v4(
    configuration: &configuration::Configuration,
    params: DeleteDomainCertV4Params,
) -> Result<(), Error<DeleteDomainCertV4Error>> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/Certificate",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDomainCertV4Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_domain_cert_v4(
    configuration: &configuration::Configuration,
    params: FetchDomainCertV4Params,
) -> Result<models::MessagingV1DomainCertV4, Error<FetchDomainCertV4Error>> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/Certificate",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1DomainCertV4`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1DomainCertV4`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchDomainCertV4Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn update_domain_cert_v4(
    configuration: &configuration::Configuration,
    params: UpdateDomainCertV4Params,
) -> Result<models::MessagingV1DomainCertV4, Error<UpdateDomainCertV4Error>> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/Certificate",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("TlsCert", params.tls_cert.to_string());
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1DomainCertV4`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1DomainCertV4`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateDomainCertV4Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
