// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_brand_registrations`]
#[derive(Clone, Debug)]
pub struct CreateBrandRegistrationsParams {
    /// Customer Profile Bundle Sid.
    pub customer_profile_bundle_sid: String,
    /// A2P Messaging Profile Bundle Sid.
    pub a2_p_profile_bundle_sid: String,
    /// Type of brand being created. One of: \\\"STANDARD\\\", \\\"SOLE_PROPRIETOR\\\". SOLE_PROPRIETOR is for low volume, SOLE_PROPRIETOR use cases. STANDARD is for all other use cases.
    pub brand_type: Option<String>,
    /// A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided.
    pub mock: Option<bool>,
    /// A flag to disable automatic secondary vetting for brands which it would otherwise be done.
    pub skip_automatic_sec_vet: Option<bool>,
}

/// struct for passing parameters to the method [`fetch_brand_registrations`]
#[derive(Clone, Debug)]
pub struct FetchBrandRegistrationsParams {
    /// The SID of the Brand Registration resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_brand_registrations`]
#[derive(Clone, Debug)]
pub struct ListBrandRegistrationsParams {
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for passing parameters to the method [`update_brand_registrations`]
#[derive(Clone, Debug)]
pub struct UpdateBrandRegistrationsParams {
    /// The SID of the Brand Registration resource to update.
    pub sid: String,
}

/// struct for typed errors of method [`create_brand_registrations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBrandRegistrationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_brand_registrations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBrandRegistrationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_brand_registrations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBrandRegistrationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_brand_registrations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateBrandRegistrationsError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_brand_registrations(
    configuration: &configuration::Configuration,
    params: CreateBrandRegistrationsParams,
) -> Result<models::MessagingV1BrandRegistrations, Error<CreateBrandRegistrationsError>> {
    let uri_str = format!("{}/v1/a2p/BrandRegistrations", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert(
        "CustomerProfileBundleSid",
        params.customer_profile_bundle_sid.to_string(),
    );
    multipart_form_params.insert(
        "A2PProfileBundleSid",
        params.a2_p_profile_bundle_sid.to_string(),
    );
    if let Some(param_value) = params.brand_type {
        multipart_form_params.insert("BrandType", param_value.to_string());
    }
    if let Some(param_value) = params.mock {
        multipart_form_params.insert("Mock", param_value.to_string());
    }
    if let Some(param_value) = params.skip_automatic_sec_vet {
        multipart_form_params.insert("SkipAutomaticSecVet", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateBrandRegistrationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_brand_registrations(
    configuration: &configuration::Configuration,
    params: FetchBrandRegistrationsParams,
) -> Result<models::MessagingV1BrandRegistrations, Error<FetchBrandRegistrationsError>> {
    let uri_str = format!(
        "{}/v1/a2p/BrandRegistrations/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBrandRegistrationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_brand_registrations(
    configuration: &configuration::Configuration,
    params: ListBrandRegistrationsParams,
) -> Result<models::ListBrandRegistrationsResponse, Error<ListBrandRegistrationsError>> {
    let uri_str = format!("{}/v1/a2p/BrandRegistrations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListBrandRegistrationsResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListBrandRegistrationsResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListBrandRegistrationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn update_brand_registrations(
    configuration: &configuration::Configuration,
    params: UpdateBrandRegistrationsParams,
) -> Result<models::MessagingV1BrandRegistrations, Error<UpdateBrandRegistrationsError>> {
    let uri_str = format!(
        "{}/v1/a2p/BrandRegistrations/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1BrandRegistrations`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateBrandRegistrationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
