// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`fetch_us_app_to_person_usecase`]
#[derive(Clone, Debug)]
pub struct FetchUsAppToPersonUsecaseParams {
    /// The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from.
    pub messaging_service_sid: String,
    /// The unique string to identify the A2P brand.
    pub brand_registration_sid: Option<String>,
}

/// struct for typed errors of method [`fetch_us_app_to_person_usecase`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUsAppToPersonUsecaseError {
    UnknownValue(serde_json::Value),
}

///
pub async fn fetch_us_app_to_person_usecase(
    configuration: &configuration::Configuration,
    params: FetchUsAppToPersonUsecaseParams,
) -> Result<models::MessagingV1ServiceUsAppToPersonUsecase, Error<FetchUsAppToPersonUsecaseError>> {
    let uri_str = format!(
        "{}/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/Usecases",
        configuration.base_path,
        MessagingServiceSid = crate::apis::urlencode(params.messaging_service_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.brand_registration_sid {
        req_builder = req_builder.query(&[("BrandRegistrationSid", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonUsecase`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceUsAppToPersonUsecase`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUsAppToPersonUsecaseError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
