// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`fetch_domain_dns_validation`]
#[derive(Clone, Debug)]
pub struct FetchDomainDnsValidationParams {
    /// Unique string used to identify the domain.
    pub domain_sid: String,
}

/// struct for typed errors of method [`fetch_domain_dns_validation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchDomainDnsValidationError {
    UnknownValue(serde_json::Value),
}

///
pub async fn fetch_domain_dns_validation(
    configuration: &configuration::Configuration,
    params: FetchDomainDnsValidationParams,
) -> Result<models::MessagingV1DomainDnsValidation, Error<FetchDomainDnsValidationError>> {
    let uri_str = format!(
        "{}/v1/LinkShortening/Domains/{DomainSid}/ValidateDns",
        configuration.base_path,
        DomainSid = crate::apis::urlencode(params.domain_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1DomainDnsValidation`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1DomainDnsValidation`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchDomainDnsValidationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
