// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_service`]
#[derive(Clone, Debug)]
pub struct CreateServiceParams {
    /// A descriptive string that you create to describe the resource. It can be up to 64 characters long.
    pub friendly_name: String,
    /// The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
    pub inbound_request_url: Option<String>,
    /// The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
    pub inbound_method: Option<String>,
    /// The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
    pub fallback_url: Option<String>,
    /// The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
    pub fallback_method: Option<String>,
    /// The URL we should call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
    pub status_callback: Option<String>,
    /// Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance.
    pub sticky_sender: Option<bool>,
    /// Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance.
    pub mms_converter: Option<bool>,
    /// Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance.
    pub smart_encoding: Option<bool>,
    pub scan_message_content: Option<models::ServiceEnumScanMessageContent>,
    /// [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures.
    pub fallback_to_long_code: Option<bool>,
    /// Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance.
    pub area_code_geomatch: Option<bool>,
    /// How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `36,000`. Default value is `36,000`.
    pub validity_period: Option<i32>,
    /// Reserved.
    pub synchronous_validation: Option<bool>,
    /// A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`.
    pub usecase: Option<String>,
    /// A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service.
    pub use_inbound_webhook_on_number: Option<bool>,
}

/// struct for passing parameters to the method [`delete_service`]
#[derive(Clone, Debug)]
pub struct DeleteServiceParams {
    /// The SID of the Service resource to delete.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_service`]
#[derive(Clone, Debug)]
pub struct FetchServiceParams {
    /// The SID of the Service resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_service`]
#[derive(Clone, Debug)]
pub struct ListServiceParams {
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for passing parameters to the method [`update_service`]
#[derive(Clone, Debug)]
pub struct UpdateServiceParams {
    /// The SID of the Service resource to update.
    pub sid: String,
    /// A descriptive string that you create to describe the resource. It can be up to 64 characters long.
    pub friendly_name: Option<String>,
    /// The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
    pub inbound_request_url: Option<String>,
    /// The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
    pub inbound_method: Option<String>,
    /// The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
    pub fallback_url: Option<String>,
    /// The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
    pub fallback_method: Option<String>,
    /// The URL we should call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
    pub status_callback: Option<String>,
    /// Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance.
    pub sticky_sender: Option<bool>,
    /// Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance.
    pub mms_converter: Option<bool>,
    /// Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance.
    pub smart_encoding: Option<bool>,
    pub scan_message_content: Option<models::ServiceEnumScanMessageContent>,
    /// [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures.
    pub fallback_to_long_code: Option<bool>,
    /// Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance.
    pub area_code_geomatch: Option<bool>,
    /// How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `36,000`. Default value is `36,000`.
    pub validity_period: Option<i32>,
    /// Reserved.
    pub synchronous_validation: Option<bool>,
    /// A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`.
    pub usecase: Option<String>,
    /// A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service.
    pub use_inbound_webhook_on_number: Option<bool>,
}

/// struct for typed errors of method [`create_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateServiceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteServiceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchServiceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListServiceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateServiceError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_service(
    configuration: &configuration::Configuration,
    params: CreateServiceParams,
) -> Result<models::MessagingV1Service, Error<CreateServiceError>> {
    let uri_str = format!("{}/v1/Services", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("FriendlyName", params.friendly_name.to_string());
    if let Some(param_value) = params.inbound_request_url {
        multipart_form_params.insert("InboundRequestUrl", param_value.to_string());
    }
    if let Some(param_value) = params.inbound_method {
        multipart_form_params.insert("InboundMethod", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_url {
        multipart_form_params.insert("FallbackUrl", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_method {
        multipart_form_params.insert("FallbackMethod", param_value.to_string());
    }
    if let Some(param_value) = params.status_callback {
        multipart_form_params.insert("StatusCallback", param_value.to_string());
    }
    if let Some(param_value) = params.sticky_sender {
        multipart_form_params.insert("StickySender", param_value.to_string());
    }
    if let Some(param_value) = params.mms_converter {
        multipart_form_params.insert("MmsConverter", param_value.to_string());
    }
    if let Some(param_value) = params.smart_encoding {
        multipart_form_params.insert("SmartEncoding", param_value.to_string());
    }
    if let Some(param_value) = params.scan_message_content {
        multipart_form_params.insert("ScanMessageContent", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_to_long_code {
        multipart_form_params.insert("FallbackToLongCode", param_value.to_string());
    }
    if let Some(param_value) = params.area_code_geomatch {
        multipart_form_params.insert("AreaCodeGeomatch", param_value.to_string());
    }
    if let Some(param_value) = params.validity_period {
        multipart_form_params.insert("ValidityPeriod", param_value.to_string());
    }
    if let Some(param_value) = params.synchronous_validation {
        multipart_form_params.insert("SynchronousValidation", param_value.to_string());
    }
    if let Some(param_value) = params.usecase {
        multipart_form_params.insert("Usecase", param_value.to_string());
    }
    if let Some(param_value) = params.use_inbound_webhook_on_number {
        multipart_form_params.insert("UseInboundWebhookOnNumber", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1Service`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1Service`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateServiceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_service(
    configuration: &configuration::Configuration,
    params: DeleteServiceParams,
) -> Result<(), Error<DeleteServiceError>> {
    let uri_str = format!(
        "{}/v1/Services/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteServiceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_service(
    configuration: &configuration::Configuration,
    params: FetchServiceParams,
) -> Result<models::MessagingV1Service, Error<FetchServiceError>> {
    let uri_str = format!(
        "{}/v1/Services/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1Service`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1Service`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchServiceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_service(
    configuration: &configuration::Configuration,
    params: ListServiceParams,
) -> Result<models::ListServiceResponse, Error<ListServiceError>> {
    let uri_str = format!("{}/v1/Services", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListServiceResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListServiceResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListServiceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn update_service(
    configuration: &configuration::Configuration,
    params: UpdateServiceParams,
) -> Result<models::MessagingV1Service, Error<UpdateServiceError>> {
    let uri_str = format!(
        "{}/v1/Services/{Sid}",
        configuration.base_path,
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    if let Some(param_value) = params.friendly_name {
        multipart_form_params.insert("FriendlyName", param_value.to_string());
    }
    if let Some(param_value) = params.inbound_request_url {
        multipart_form_params.insert("InboundRequestUrl", param_value.to_string());
    }
    if let Some(param_value) = params.inbound_method {
        multipart_form_params.insert("InboundMethod", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_url {
        multipart_form_params.insert("FallbackUrl", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_method {
        multipart_form_params.insert("FallbackMethod", param_value.to_string());
    }
    if let Some(param_value) = params.status_callback {
        multipart_form_params.insert("StatusCallback", param_value.to_string());
    }
    if let Some(param_value) = params.sticky_sender {
        multipart_form_params.insert("StickySender", param_value.to_string());
    }
    if let Some(param_value) = params.mms_converter {
        multipart_form_params.insert("MmsConverter", param_value.to_string());
    }
    if let Some(param_value) = params.smart_encoding {
        multipart_form_params.insert("SmartEncoding", param_value.to_string());
    }
    if let Some(param_value) = params.scan_message_content {
        multipart_form_params.insert("ScanMessageContent", param_value.to_string());
    }
    if let Some(param_value) = params.fallback_to_long_code {
        multipart_form_params.insert("FallbackToLongCode", param_value.to_string());
    }
    if let Some(param_value) = params.area_code_geomatch {
        multipart_form_params.insert("AreaCodeGeomatch", param_value.to_string());
    }
    if let Some(param_value) = params.validity_period {
        multipart_form_params.insert("ValidityPeriod", param_value.to_string());
    }
    if let Some(param_value) = params.synchronous_validation {
        multipart_form_params.insert("SynchronousValidation", param_value.to_string());
    }
    if let Some(param_value) = params.usecase {
        multipart_form_params.insert("Usecase", param_value.to_string());
    }
    if let Some(param_value) = params.use_inbound_webhook_on_number {
        multipart_form_params.insert("UseInboundWebhookOnNumber", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1Service`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1Service`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateServiceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
