// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_alpha_sender`]
#[derive(Clone, Debug)]
pub struct CreateAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under.
    pub service_sid: String,
    /// The Alphanumeric Sender ID string. Can be up to 11 characters long. Valid characters are A-Z, a-z, 0-9, space, hyphen `-`, plus `+`, underscore `_` and ampersand `&`. This value cannot contain only numbers.
    pub alpha_sender: String,
}

/// struct for passing parameters to the method [`delete_alpha_sender`]
#[derive(Clone, Debug)]
pub struct DeleteAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from.
    pub service_sid: String,
    /// The SID of the AlphaSender resource to delete.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_alpha_sender`]
#[derive(Clone, Debug)]
pub struct FetchAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from.
    pub service_sid: String,
    /// The SID of the AlphaSender resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_alpha_sender`]
#[derive(Clone, Debug)]
pub struct ListAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from.
    pub service_sid: String,
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for typed errors of method [`create_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAlphaSenderError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_alpha_sender(
    configuration: &configuration::Configuration,
    params: CreateAlphaSenderParams,
) -> Result<models::MessagingV1ServiceAlphaSender, Error<CreateAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/AlphaSenders",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("AlphaSender", params.alpha_sender.to_string());
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceAlphaSender`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceAlphaSender`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_alpha_sender(
    configuration: &configuration::Configuration,
    params: DeleteAlphaSenderParams,
) -> Result<(), Error<DeleteAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/AlphaSenders/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_alpha_sender(
    configuration: &configuration::Configuration,
    params: FetchAlphaSenderParams,
) -> Result<models::MessagingV1ServiceAlphaSender, Error<FetchAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/AlphaSenders/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceAlphaSender`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceAlphaSender`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_alpha_sender(
    configuration: &configuration::Configuration,
    params: ListAlphaSenderParams,
) -> Result<models::ListAlphaSenderResponse, Error<ListAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/AlphaSenders",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListAlphaSenderResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListAlphaSenderResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
