// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_destination_alpha_sender`]
#[derive(Clone, Debug)]
pub struct CreateDestinationAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under.
    pub service_sid: String,
    /// The Alphanumeric Sender ID string. Can be up to 11 characters long. Valid characters are A-Z, a-z, 0-9, space, hyphen `-`, plus `+`, underscore `_` and ampersand `&`. This value cannot contain only numbers.
    pub alpha_sender: String,
    /// The Optional Two Character ISO Country Code the Alphanumeric Sender ID will be used for. If the IsoCountryCode is not provided, a default Alpha Sender will be created that can be used across all countries.
    pub iso_country_code: Option<String>,
}

/// struct for passing parameters to the method [`delete_destination_alpha_sender`]
#[derive(Clone, Debug)]
pub struct DeleteDestinationAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from.
    pub service_sid: String,
    /// The SID of the AlphaSender resource to delete.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_destination_alpha_sender`]
#[derive(Clone, Debug)]
pub struct FetchDestinationAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from.
    pub service_sid: String,
    /// The SID of the AlphaSender resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_destination_alpha_sender`]
#[derive(Clone, Debug)]
pub struct ListDestinationAlphaSenderParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from.
    pub service_sid: String,
    /// Optional filter to return only alphanumeric sender IDs associated with the specified two-character ISO country code.
    pub iso_country_code: Option<String>,
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for typed errors of method [`create_destination_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateDestinationAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_destination_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDestinationAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_destination_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchDestinationAlphaSenderError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_destination_alpha_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDestinationAlphaSenderError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_destination_alpha_sender(
    configuration: &configuration::Configuration,
    params: CreateDestinationAlphaSenderParams,
) -> Result<
    models::MessagingV1ServiceDestinationAlphaSender,
    Error<CreateDestinationAlphaSenderError>,
> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/DestinationAlphaSenders",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("AlphaSender", params.alpha_sender.to_string());
    if let Some(param_value) = params.iso_country_code {
        multipart_form_params.insert("IsoCountryCode", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceDestinationAlphaSender`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceDestinationAlphaSender`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateDestinationAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_destination_alpha_sender(
    configuration: &configuration::Configuration,
    params: DeleteDestinationAlphaSenderParams,
) -> Result<(), Error<DeleteDestinationAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/DestinationAlphaSenders/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteDestinationAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_destination_alpha_sender(
    configuration: &configuration::Configuration,
    params: FetchDestinationAlphaSenderParams,
) -> Result<models::MessagingV1ServiceDestinationAlphaSender, Error<FetchDestinationAlphaSenderError>>
{
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/DestinationAlphaSenders/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServiceDestinationAlphaSender`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServiceDestinationAlphaSender`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchDestinationAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_destination_alpha_sender(
    configuration: &configuration::Configuration,
    params: ListDestinationAlphaSenderParams,
) -> Result<models::ListDestinationAlphaSenderResponse, Error<ListDestinationAlphaSenderError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/DestinationAlphaSenders",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.iso_country_code {
        req_builder = req_builder.query(&[("IsoCountryCode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListDestinationAlphaSenderResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListDestinationAlphaSenderResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListDestinationAlphaSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
