// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_brand_vetting`]
#[derive(Clone, Debug)]
pub struct CreateBrandVettingParams {
    /// The SID of the Brand Registration resource of the vettings to create .
    pub brand_sid: String,
    pub vetting_provider: models::BrandVettingEnumVettingProvider,
    /// The unique ID of the vetting
    pub vetting_id: Option<String>,
}

/// struct for passing parameters to the method [`fetch_brand_vetting`]
#[derive(Clone, Debug)]
pub struct FetchBrandVettingParams {
    /// The SID of the Brand Registration resource of the vettings to read .
    pub brand_sid: String,
    /// The Twilio SID of the third-party vetting record.
    pub brand_vetting_sid: String,
}

/// struct for passing parameters to the method [`list_brand_vetting`]
#[derive(Clone, Debug)]
pub struct ListBrandVettingParams {
    /// The SID of the Brand Registration resource of the vettings to read .
    pub brand_sid: String,
    /// The third-party provider of the vettings to read
    pub vetting_provider: Option<models::BrandVettingEnumVettingProvider>,
}

/// struct for typed errors of method [`create_brand_vetting`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBrandVettingError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_brand_vetting`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBrandVettingError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_brand_vetting`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBrandVettingError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_brand_vetting(
    configuration: &configuration::Configuration,
    params: CreateBrandVettingParams,
) -> Result<models::MessagingV1BrandRegistrationsBrandVetting, Error<CreateBrandVettingError>> {
    let uri_str = format!(
        "{}/v1/a2p/BrandRegistrations/{BrandSid}/Vettings",
        configuration.base_path,
        BrandSid = crate::apis::urlencode(params.brand_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("VettingProvider", params.vetting_provider.to_string());
    if let Some(param_value) = params.vetting_id {
        multipart_form_params.insert("VettingId", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1BrandRegistrationsBrandVetting`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1BrandRegistrationsBrandVetting`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateBrandVettingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_brand_vetting(
    configuration: &configuration::Configuration,
    params: FetchBrandVettingParams,
) -> Result<models::MessagingV1BrandRegistrationsBrandVetting, Error<FetchBrandVettingError>> {
    let uri_str = format!(
        "{}/v1/a2p/BrandRegistrations/{BrandSid}/Vettings/{BrandVettingSid}",
        configuration.base_path,
        BrandSid = crate::apis::urlencode(params.brand_sid),
        BrandVettingSid = crate::apis::urlencode(params.brand_vetting_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1BrandRegistrationsBrandVetting`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1BrandRegistrationsBrandVetting`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBrandVettingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_brand_vetting(
    configuration: &configuration::Configuration,
    params: ListBrandVettingParams,
) -> Result<models::ListBrandVettingResponse, Error<ListBrandVettingError>> {
    let uri_str = format!(
        "{}/v1/a2p/BrandRegistrations/{BrandSid}/Vettings",
        configuration.base_path,
        BrandSid = crate::apis::urlencode(params.brand_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.vetting_provider {
        req_builder = req_builder.query(&[("VettingProvider", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListBrandVettingResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListBrandVettingResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListBrandVettingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
