// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`fetch_deactivation`]
#[derive(Clone, Debug)]
pub struct FetchDeactivationParams {
    /// The request will return a list of all United States Phone Numbers that were deactivated on the day specified by this parameter. This date should be specified in YYYY-MM-DD format.
    pub date: Option<chrono::NaiveDate>,
}

/// struct for typed errors of method [`fetch_deactivation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchDeactivationError {
    UnknownValue(serde_json::Value),
}

/// Fetch a list of all United States numbers that have been deactivated on a specific date.
pub async fn fetch_deactivation(
    configuration: &configuration::Configuration,
    params: FetchDeactivationParams,
) -> Result<(), Error<FetchDeactivationError>> {
    let uri_str = format!("{}/v1/Deactivations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.date {
        req_builder = req_builder.query(&[("Date", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchDeactivationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
