// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_phone_number`]
#[derive(Clone, Debug)]
pub struct CreatePhoneNumberParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under.
    pub service_sid: String,
    /// The SID of the Phone Number being added to the Service.
    pub phone_number_sid: String,
}

/// struct for passing parameters to the method [`delete_phone_number`]
#[derive(Clone, Debug)]
pub struct DeletePhoneNumberParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from.
    pub service_sid: String,
    /// The SID of the PhoneNumber resource to delete.
    pub sid: String,
}

/// struct for passing parameters to the method [`fetch_phone_number`]
#[derive(Clone, Debug)]
pub struct FetchPhoneNumberParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from.
    pub service_sid: String,
    /// The SID of the PhoneNumber resource to fetch.
    pub sid: String,
}

/// struct for passing parameters to the method [`list_phone_number`]
#[derive(Clone, Debug)]
pub struct ListPhoneNumberParams {
    /// The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from.
    pub service_sid: String,
    /// How many resources to return in each list page. The default is 50, and the maximum is 1000.
    pub page_size: Option<u64>,
    /// The page index. This value is simply for client state.
    pub page: Option<u32>,
    /// The page token. This is provided by the API.
    pub page_token: Option<String>,
}

/// struct for typed errors of method [`create_phone_number`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePhoneNumberError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_phone_number`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePhoneNumberError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_phone_number`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchPhoneNumberError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_phone_number`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListPhoneNumberError {
    UnknownValue(serde_json::Value),
}

///
pub async fn create_phone_number(
    configuration: &configuration::Configuration,
    params: CreatePhoneNumberParams,
) -> Result<models::MessagingV1ServicePhoneNumber, Error<CreatePhoneNumberError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/PhoneNumbers",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = super::FormParams::default();
    multipart_form_params.insert("PhoneNumberSid", params.phone_number_sid.to_string());
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServicePhoneNumber`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServicePhoneNumber`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePhoneNumberError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn delete_phone_number(
    configuration: &configuration::Configuration,
    params: DeletePhoneNumberParams,
) -> Result<(), Error<DeletePhoneNumberError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/PhoneNumbers/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeletePhoneNumberError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn fetch_phone_number(
    configuration: &configuration::Configuration,
    params: FetchPhoneNumberParams,
) -> Result<models::MessagingV1ServicePhoneNumber, Error<FetchPhoneNumberError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/PhoneNumbers/{Sid}",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid),
        Sid = crate::apis::urlencode(params.sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::MessagingV1ServicePhoneNumber`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::MessagingV1ServicePhoneNumber`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchPhoneNumberError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

///
pub async fn list_phone_number(
    configuration: &configuration::Configuration,
    params: ListPhoneNumberParams,
) -> Result<models::ListPhoneNumberResponse, Error<ListPhoneNumberError>> {
    let uri_str = format!(
        "{}/v1/Services/{ServiceSid}/PhoneNumbers",
        configuration.base_path,
        ServiceSid = crate::apis::urlencode(params.service_sid)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.page_size {
        req_builder = req_builder.query(&[("PageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("Page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page_token {
        req_builder = req_builder.query(&[("PageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ListPhoneNumberResponse`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ListPhoneNumberResponse`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListPhoneNumberError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
