// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV2010AccountOutgoingCallerIdSmsVerificationSendCodeAttemptsInner {
    /// The SID of the verification attempt.
    #[serde(rename = "attempt_sid", skip_serializing_if = "Option::is_none")]
    pub attempt_sid: Option<String>,
    /// The date and time of the attempt in ISO 8601 format.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl ApiV2010AccountOutgoingCallerIdSmsVerificationSendCodeAttemptsInner {
    pub fn new() -> ApiV2010AccountOutgoingCallerIdSmsVerificationSendCodeAttemptsInner {
        ApiV2010AccountOutgoingCallerIdSmsVerificationSendCodeAttemptsInner {
            attempt_sid: None,
            time: None,
        }
    }
}
