// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV2010AccountOutgoingCallerIdSmsVerification {
    /// The phone number being verified in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
    #[serde(
        rename = "phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// The SID that uniquely identifies the verification.
    #[serde(
        rename = "verification_sid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub verification_sid: Option<Option<String>>,
    /// An array of verification attempt objects containing the channel attempted and the channel-specific transaction SID.
    #[serde(
        rename = "send_code_attempts",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub send_code_attempts: Option<
        Option<Vec<models::ApiV2010AccountOutgoingCallerIdSmsVerificationSendCodeAttemptsInner>>,
    >,
}

impl ApiV2010AccountOutgoingCallerIdSmsVerification {
    pub fn new() -> ApiV2010AccountOutgoingCallerIdSmsVerification {
        ApiV2010AccountOutgoingCallerIdSmsVerification {
            phone_number: None,
            verification_sid: None,
            send_code_attempts: None,
        }
    }
}
