// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthorizedConnectAppEnumPermission : The set of permissions that you authorized for the Connect App.  Can be: `get-all` or `post-all`.
/// The set of permissions that you authorized for the Connect App.  Can be: `get-all` or `post-all`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum AuthorizedConnectAppEnumPermission {
    GetAll,
    PostAll,

    Unknown(String),
}

impl AuthorizedConnectAppEnumPermission {
    pub fn as_str(&self) -> &str {
        match self {
            Self::GetAll => "get-all",
            Self::PostAll => "post-all",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for AuthorizedConnectAppEnumPermission {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for AuthorizedConnectAppEnumPermission {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "get-all" => Self::GetAll,
            "post-all" => Self::PostAll,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for AuthorizedConnectAppEnumPermission {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for AuthorizedConnectAppEnumPermission {
    fn default() -> AuthorizedConnectAppEnumPermission {
        Self::GetAll
    }
}
