// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// CallEnumStatus : The status of this call. Can be: `queued`, `ringing`, `in-progress`, `canceled`, `completed`, `failed`, `busy` or `no-answer`. See [Call Status Values](https://www.twilio.com/docs/voice/api/call-resource#call-status-values) below for more information.
/// The status of this call. Can be: `queued`, `ringing`, `in-progress`, `canceled`, `completed`, `failed`, `busy` or `no-answer`. See [Call Status Values](https://www.twilio.com/docs/voice/api/call-resource#call-status-values) below for more information.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum CallEnumStatus {
    Queued,
    Ringing,
    InProgress,
    Completed,
    Busy,
    Failed,
    NoAnswer,
    Canceled,

    Unknown(String),
}

impl CallEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Queued => "queued",
            Self::Ringing => "ringing",
            Self::InProgress => "in-progress",
            Self::Completed => "completed",
            Self::Busy => "busy",
            Self::Failed => "failed",
            Self::NoAnswer => "no-answer",
            Self::Canceled => "canceled",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for CallEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for CallEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "queued" => Self::Queued,
            "ringing" => Self::Ringing,
            "in-progress" => Self::InProgress,
            "completed" => Self::Completed,
            "busy" => Self::Busy,
            "failed" => Self::Failed,
            "no-answer" => Self::NoAnswer,
            "canceled" => Self::Canceled,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for CallEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for CallEnumStatus {
    fn default() -> CallEnumStatus {
        Self::Queued
    }
}
