// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// CallRecordingEnumSource : How the recording was created. Can be: `DialVerb`, `Conference`, `OutboundAPI`, `Trunking`, `RecordVerb`, `StartCallRecordingAPI`, and `StartConferenceRecordingAPI`.
/// How the recording was created. Can be: `DialVerb`, `Conference`, `OutboundAPI`, `Trunking`, `RecordVerb`, `StartCallRecordingAPI`, and `StartConferenceRecordingAPI`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum CallRecordingEnumSource {
    DialVerb,
    Conference,
    OutboundApi,
    Trunking,
    RecordVerb,
    StartCallRecordingApi,
    StartConferenceRecordingApi,

    Unknown(String),
}

impl CallRecordingEnumSource {
    pub fn as_str(&self) -> &str {
        match self {
            Self::DialVerb => "DialVerb",
            Self::Conference => "Conference",
            Self::OutboundApi => "OutboundAPI",
            Self::Trunking => "Trunking",
            Self::RecordVerb => "RecordVerb",
            Self::StartCallRecordingApi => "StartCallRecordingAPI",
            Self::StartConferenceRecordingApi => "StartConferenceRecordingAPI",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for CallRecordingEnumSource {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for CallRecordingEnumSource {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "DialVerb" => Self::DialVerb,
            "Conference" => Self::Conference,
            "OutboundAPI" => Self::OutboundApi,
            "Trunking" => Self::Trunking,
            "RecordVerb" => Self::RecordVerb,
            "StartCallRecordingAPI" => Self::StartCallRecordingApi,
            "StartConferenceRecordingAPI" => Self::StartConferenceRecordingApi,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for CallRecordingEnumSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for CallRecordingEnumSource {
    fn default() -> CallRecordingEnumSource {
        Self::DialVerb
    }
}
