// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum CallEnumEvent {
    Initiated,
    Ringing,
    Answered,
    Completed,

    Unknown(String),
}

impl CallEnumEvent {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Initiated => "initiated",
            Self::Ringing => "ringing",
            Self::Answered => "answered",
            Self::Completed => "completed",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for CallEnumEvent {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for CallEnumEvent {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "initiated" => Self::Initiated,
            "ringing" => Self::Ringing,
            "answered" => Self::Answered,
            "completed" => Self::Completed,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for CallEnumEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for CallEnumEvent {
    fn default() -> CallEnumEvent {
        Self::Initiated
    }
}
