// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// ConferenceEnumReasonConferenceEnded : The reason why a conference ended. When a conference is in progress, will be `null`. When conference is completed, can be: `conference-ended-via-api`, `participant-with-end-conference-on-exit-left`, `participant-with-end-conference-on-exit-kicked`, `last-participant-kicked`, or `last-participant-left`.
/// The reason why a conference ended. When a conference is in progress, will be `null`. When conference is completed, can be: `conference-ended-via-api`, `participant-with-end-conference-on-exit-left`, `participant-with-end-conference-on-exit-kicked`, `last-participant-kicked`, or `last-participant-left`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum ConferenceEnumReasonConferenceEnded {
    ConferenceEndedViaApi,
    ParticipantWithEndConferenceOnExitLeft,
    ParticipantWithEndConferenceOnExitKicked,
    LastParticipantKicked,
    LastParticipantLeft,

    Unknown(String),
}

impl ConferenceEnumReasonConferenceEnded {
    pub fn as_str(&self) -> &str {
        match self {
            Self::ConferenceEndedViaApi => "conference-ended-via-api",
            Self::ParticipantWithEndConferenceOnExitLeft => {
                "participant-with-end-conference-on-exit-left"
            }
            Self::ParticipantWithEndConferenceOnExitKicked => {
                "participant-with-end-conference-on-exit-kicked"
            }
            Self::LastParticipantKicked => "last-participant-kicked",
            Self::LastParticipantLeft => "last-participant-left",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ConferenceEnumReasonConferenceEnded {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ConferenceEnumReasonConferenceEnded {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "conference-ended-via-api" => Self::ConferenceEndedViaApi,
            "participant-with-end-conference-on-exit-left" => {
                Self::ParticipantWithEndConferenceOnExitLeft
            }
            "participant-with-end-conference-on-exit-kicked" => {
                Self::ParticipantWithEndConferenceOnExitKicked
            }
            "last-participant-kicked" => Self::LastParticipantKicked,
            "last-participant-left" => Self::LastParticipantLeft,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for ConferenceEnumReasonConferenceEnded {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for ConferenceEnumReasonConferenceEnded {
    fn default() -> ConferenceEnumReasonConferenceEnded {
        Self::ConferenceEndedViaApi
    }
}
