// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectAppEnumPermission : The set of permissions that your ConnectApp requests.
/// The set of permissions that your ConnectApp requests.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum ConnectAppEnumPermission {
    GetAll,
    PostAll,

    Unknown(String),
}

impl ConnectAppEnumPermission {
    pub fn as_str(&self) -> &str {
        match self {
            Self::GetAll => "get-all",
            Self::PostAll => "post-all",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ConnectAppEnumPermission {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ConnectAppEnumPermission {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "get-all" => Self::GetAll,
            "post-all" => Self::PostAll,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for ConnectAppEnumPermission {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for ConnectAppEnumPermission {
    fn default() -> ConnectAppEnumPermission {
        Self::GetAll
    }
}
