// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomingPhoneNumberTollFreeEnumAddressRequirement : Whether the phone number requires an [Address](https://www.twilio.com/docs/usage/api/address) registered with Twilio. Can be: `none`, `any`, `local`, or `foreign`.
/// Whether the phone number requires an [Address](https://www.twilio.com/docs/usage/api/address) registered with Twilio. Can be: `none`, `any`, `local`, or `foreign`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum IncomingPhoneNumberTollFreeEnumAddressRequirement {
    None,
    Any,
    Local,
    Foreign,

    Unknown(String),
}

impl IncomingPhoneNumberTollFreeEnumAddressRequirement {
    pub fn as_str(&self) -> &str {
        match self {
            Self::None => "none",
            Self::Any => "any",
            Self::Local => "local",
            Self::Foreign => "foreign",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "none" => Self::None,
            "any" => Self::Any,
            "local" => Self::Local,
            "foreign" => Self::Foreign,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn default() -> IncomingPhoneNumberTollFreeEnumAddressRequirement {
        Self::None
    }
}
