// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomingPhoneNumberLocalEnumEmergencyAddressStatus : The status of address registration with emergency services. A registered emergency address will be used during handling of emergency calls from this number.
/// The status of address registration with emergency services. A registered emergency address will be used during handling of emergency calls from this number.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    Registered,
    Unregistered,
    PendingRegistration,
    RegistrationFailure,
    PendingUnregistration,
    UnregistrationFailure,

    Unknown(String),
}

impl IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Registered => "registered",
            Self::Unregistered => "unregistered",
            Self::PendingRegistration => "pending-registration",
            Self::RegistrationFailure => "registration-failure",
            Self::PendingUnregistration => "pending-unregistration",
            Self::UnregistrationFailure => "unregistration-failure",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "registered" => Self::Registered,
            "unregistered" => Self::Unregistered,
            "pending-registration" => Self::PendingRegistration,
            "registration-failure" => Self::RegistrationFailure,
            "pending-unregistration" => Self::PendingUnregistration,
            "unregistration-failure" => Self::UnregistrationFailure,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
    fn default() -> IncomingPhoneNumberLocalEnumEmergencyAddressStatus {
        Self::Registered
    }
}
