// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    Voice,
    Fax,

    Unknown(String),
}

impl IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Voice => "voice",
            Self::Fax => "fax",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "voice" => Self::Voice,
            "fax" => Self::Fax,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for IncomingPhoneNumberMobileEnumVoiceReceiveMode {
    fn default() -> IncomingPhoneNumberMobileEnumVoiceReceiveMode {
        Self::Voice
    }
}
