// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// IncomingPhoneNumberEnumEmergencyStatus : The parameter displays if emergency calling is enabled for this number. Active numbers may place emergency calls by dialing valid emergency numbers for the country.
/// The parameter displays if emergency calling is enabled for this number. Active numbers may place emergency calls by dialing valid emergency numbers for the country.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum IncomingPhoneNumberEnumEmergencyStatus {
    Active,
    Inactive,

    Unknown(String),
}

impl IncomingPhoneNumberEnumEmergencyStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Active => "Active",
            Self::Inactive => "Inactive",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for IncomingPhoneNumberEnumEmergencyStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for IncomingPhoneNumberEnumEmergencyStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "Active" => Self::Active,
            "Inactive" => Self::Inactive,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for IncomingPhoneNumberEnumEmergencyStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for IncomingPhoneNumberEnumEmergencyStatus {
    fn default() -> IncomingPhoneNumberEnumEmergencyStatus {
        Self::Active
    }
}
