// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageEnumScheduleType : For Messaging Services only: Include this parameter with a value of `fixed` in conjuction with the `send_time` parameter in order to [schedule a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).
/// For Messaging Services only: Include this parameter with a value of `fixed` in conjuction with the `send_time` parameter in order to [schedule a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum MessageEnumScheduleType {
    Fixed,

    Unknown(String),
}

impl MessageEnumScheduleType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Fixed => "fixed",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for MessageEnumScheduleType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for MessageEnumScheduleType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "fixed" => Self::Fixed,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for MessageEnumScheduleType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for MessageEnumScheduleType {
    fn default() -> MessageEnumScheduleType {
        Self::Fixed
    }
}
