// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageEnumContentRetention : Determines if the message content can be stored or redacted based on privacy settings
/// Determines if the message content can be stored or redacted based on privacy settings
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum MessageEnumContentRetention {
    Retain,
    Discard,

    Unknown(String),
}

impl MessageEnumContentRetention {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Retain => "retain",
            Self::Discard => "discard",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for MessageEnumContentRetention {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for MessageEnumContentRetention {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "retain" => Self::Retain,
            "discard" => Self::Discard,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for MessageEnumContentRetention {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for MessageEnumContentRetention {
    fn default() -> MessageEnumContentRetention {
        Self::Retain
    }
}
