// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// ParticipantEnumStatus : The status of the participant's call in a session. Can be: `queued`, `connecting`, `ringing`, `connected`, `complete`, or `failed`.
/// The status of the participant's call in a session. Can be: `queued`, `connecting`, `ringing`, `connected`, `complete`, or `failed`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum ParticipantEnumStatus {
    Queued,
    Connecting,
    Ringing,
    Connected,
    Complete,
    Failed,

    Unknown(String),
}

impl ParticipantEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Queued => "queued",
            Self::Connecting => "connecting",
            Self::Ringing => "ringing",
            Self::Connected => "connected",
            Self::Complete => "complete",
            Self::Failed => "failed",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for ParticipantEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for ParticipantEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "queued" => Self::Queued,
            "connecting" => Self::Connecting,
            "ringing" => Self::Ringing,
            "connected" => Self::Connected,
            "complete" => Self::Complete,
            "failed" => Self::Failed,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for ParticipantEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for ParticipantEnumStatus {
    fn default() -> ParticipantEnumStatus {
        Self::Queued
    }
}
