// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentsEnumCapture : The piece of payment information that you wish the caller to enter. Must be one of `payment-card-number`, `expiration-date`, `security-code`, `postal-code`, `bank-routing-number`, `bank-account-number`, or their `-matcher` variants for input confirmation when `RequireMatchingInputs` is enabled.
/// The piece of payment information that you wish the caller to enter. Must be one of `payment-card-number`, `expiration-date`, `security-code`, `postal-code`, `bank-routing-number`, `bank-account-number`, or their `-matcher` variants for input confirmation when `RequireMatchingInputs` is enabled.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum PaymentsEnumCapture {
    PaymentCardNumber,
    ExpirationDate,
    SecurityCode,
    PostalCode,
    BankRoutingNumber,
    BankAccountNumber,
    PaymentCardNumberMatcher,
    ExpirationDateMatcher,
    SecurityCodeMatcher,
    PostalCodeMatcher,

    Unknown(String),
}

impl PaymentsEnumCapture {
    pub fn as_str(&self) -> &str {
        match self {
            Self::PaymentCardNumber => "payment-card-number",
            Self::ExpirationDate => "expiration-date",
            Self::SecurityCode => "security-code",
            Self::PostalCode => "postal-code",
            Self::BankRoutingNumber => "bank-routing-number",
            Self::BankAccountNumber => "bank-account-number",
            Self::PaymentCardNumberMatcher => "payment-card-number-matcher",
            Self::ExpirationDateMatcher => "expiration-date-matcher",
            Self::SecurityCodeMatcher => "security-code-matcher",
            Self::PostalCodeMatcher => "postal-code-matcher",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PaymentsEnumCapture {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PaymentsEnumCapture {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "payment-card-number" => Self::PaymentCardNumber,
            "expiration-date" => Self::ExpirationDate,
            "security-code" => Self::SecurityCode,
            "postal-code" => Self::PostalCode,
            "bank-routing-number" => Self::BankRoutingNumber,
            "bank-account-number" => Self::BankAccountNumber,
            "payment-card-number-matcher" => Self::PaymentCardNumberMatcher,
            "expiration-date-matcher" => Self::ExpirationDateMatcher,
            "security-code-matcher" => Self::SecurityCodeMatcher,
            "postal-code-matcher" => Self::PostalCodeMatcher,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for PaymentsEnumCapture {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for PaymentsEnumCapture {
    fn default() -> PaymentsEnumCapture {
        Self::PaymentCardNumber
    }
}
