// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentsEnumStatus : Indicates whether the current payment session should be cancelled or completed. When `cancel` the payment session is cancelled. When `complete`, Twilio sends the payment information to the selected Pay Connector for processing.
/// Indicates whether the current payment session should be cancelled or completed. When `cancel` the payment session is cancelled. When `complete`, Twilio sends the payment information to the selected Pay Connector for processing.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum PaymentsEnumStatus {
    Complete,
    Cancel,

    Unknown(String),
}

impl PaymentsEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Complete => "complete",
            Self::Cancel => "cancel",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PaymentsEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PaymentsEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "complete" => Self::Complete,
            "cancel" => Self::Cancel,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for PaymentsEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for PaymentsEnumStatus {
    fn default() -> PaymentsEnumStatus {
        Self::Complete
    }
}
