// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentsEnumPaymentMethod : Type of payment being captured. One of `credit-card` or `ach-debit`. The default value is `credit-card`.
/// Type of payment being captured. One of `credit-card` or `ach-debit`. The default value is `credit-card`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum PaymentsEnumPaymentMethod {
    CreditCard,
    AchDebit,

    Unknown(String),
}

impl PaymentsEnumPaymentMethod {
    pub fn as_str(&self) -> &str {
        match self {
            Self::CreditCard => "credit-card",
            Self::AchDebit => "ach-debit",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PaymentsEnumPaymentMethod {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PaymentsEnumPaymentMethod {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "credit-card" => Self::CreditCard,
            "ach-debit" => Self::AchDebit,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for PaymentsEnumPaymentMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for PaymentsEnumPaymentMethod {
    fn default() -> PaymentsEnumPaymentMethod {
        Self::CreditCard
    }
}
