// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentsEnumTokenType : Indicates whether the payment method should be tokenized as a `one-time`, `reusable`, or `payment-method` token. The default value is `reusable`. Do not enter a charge amount when tokenizing. If a charge amount is entered, the payment method will be charged and not tokenized.
/// Indicates whether the payment method should be tokenized as a `one-time`, `reusable`, or `payment-method` token. The default value is `reusable`. Do not enter a charge amount when tokenizing. If a charge amount is entered, the payment method will be charged and not tokenized.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum PaymentsEnumTokenType {
    OneTime,
    Reusable,
    PaymentMethod,

    Unknown(String),
}

impl PaymentsEnumTokenType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::OneTime => "one-time",
            Self::Reusable => "reusable",
            Self::PaymentMethod => "payment-method",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PaymentsEnumTokenType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PaymentsEnumTokenType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "one-time" => Self::OneTime,
            "reusable" => Self::Reusable,
            "payment-method" => Self::PaymentMethod,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for PaymentsEnumTokenType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for PaymentsEnumTokenType {
    fn default() -> PaymentsEnumTokenType {
        Self::OneTime
    }
}
