// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentsEnumBankAccountType : Type of bank account if payment source is ACH. One of `consumer-checking`, `consumer-savings`, or `commercial-checking`. The default value is `consumer-checking`.
/// Type of bank account if payment source is ACH. One of `consumer-checking`, `consumer-savings`, or `commercial-checking`. The default value is `consumer-checking`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum PaymentsEnumBankAccountType {
    ConsumerChecking,
    ConsumerSavings,
    CommercialChecking,

    Unknown(String),
}

impl PaymentsEnumBankAccountType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::ConsumerChecking => "consumer-checking",
            Self::ConsumerSavings => "consumer-savings",
            Self::CommercialChecking => "commercial-checking",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for PaymentsEnumBankAccountType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for PaymentsEnumBankAccountType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "consumer-checking" => Self::ConsumerChecking,
            "consumer-savings" => Self::ConsumerSavings,
            "commercial-checking" => Self::CommercialChecking,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for PaymentsEnumBankAccountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for PaymentsEnumBankAccountType {
    fn default() -> PaymentsEnumBankAccountType {
        Self::ConsumerChecking
    }
}
