// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeTranscriptionEnumStatus : The status - one of `stopped`, `in-flight`
/// The status - one of `stopped`, `in-flight`
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum RealtimeTranscriptionEnumStatus {
    InProgress,
    Stopped,

    Unknown(String),
}

impl RealtimeTranscriptionEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InProgress => "in-progress",
            Self::Stopped => "stopped",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for RealtimeTranscriptionEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for RealtimeTranscriptionEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "in-progress" => Self::InProgress,
            "stopped" => Self::Stopped,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for RealtimeTranscriptionEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for RealtimeTranscriptionEnumStatus {
    fn default() -> RealtimeTranscriptionEnumStatus {
        Self::InProgress
    }
}
