// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum RealtimeTranscriptionEnumUpdateStatus {
    Stopped,

    Unknown(String),
}

impl RealtimeTranscriptionEnumUpdateStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Stopped => "stopped",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for RealtimeTranscriptionEnumUpdateStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for RealtimeTranscriptionEnumUpdateStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "stopped" => Self::Stopped,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for RealtimeTranscriptionEnumUpdateStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for RealtimeTranscriptionEnumUpdateStatus {
    fn default() -> RealtimeTranscriptionEnumUpdateStatus {
        Self::Stopped
    }
}
