// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordingEnumStatus : The status of the recording. Can be: `processing`, `completed`, `absent` or `deleted`. For information about more detailed statuses on in-progress recordings, check out how to [Update a Recording Resource](https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource).
/// The status of the recording. Can be: `processing`, `completed`, `absent` or `deleted`. For information about more detailed statuses on in-progress recordings, check out how to [Update a Recording Resource](https://www.twilio.com/docs/voice/api/recording#update-a-recording-resource).
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum RecordingEnumStatus {
    InProgress,
    Paused,
    Stopped,
    Processing,
    Completed,
    Absent,
    Deleted,

    Unknown(String),
}

impl RecordingEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InProgress => "in-progress",
            Self::Paused => "paused",
            Self::Stopped => "stopped",
            Self::Processing => "processing",
            Self::Completed => "completed",
            Self::Absent => "absent",
            Self::Deleted => "deleted",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for RecordingEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for RecordingEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "in-progress" => Self::InProgress,
            "paused" => Self::Paused,
            "stopped" => Self::Stopped,
            "processing" => Self::Processing,
            "completed" => Self::Completed,
            "absent" => Self::Absent,
            "deleted" => Self::Deleted,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for RecordingEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for RecordingEnumStatus {
    fn default() -> RecordingEnumStatus {
        Self::InProgress
    }
}
