// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// SiprecEnumTrack : One of `inbound_track`, `outbound_track`, `both_tracks`.
/// One of `inbound_track`, `outbound_track`, `both_tracks`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum SiprecEnumTrack {
    InboundTrack,
    OutboundTrack,
    BothTracks,

    Unknown(String),
}

impl SiprecEnumTrack {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InboundTrack => "inbound_track",
            Self::OutboundTrack => "outbound_track",
            Self::BothTracks => "both_tracks",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for SiprecEnumTrack {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for SiprecEnumTrack {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "inbound_track" => Self::InboundTrack,
            "outbound_track" => Self::OutboundTrack,
            "both_tracks" => Self::BothTracks,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for SiprecEnumTrack {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for SiprecEnumTrack {
    fn default() -> SiprecEnumTrack {
        Self::InboundTrack
    }
}
