// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum SmsMessageEnumDirection {
    Inbound,
    OutboundApi,
    OutboundCall,
    OutboundReply,

    Unknown(String),
}

impl SmsMessageEnumDirection {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Inbound => "inbound",
            Self::OutboundApi => "outbound-api",
            Self::OutboundCall => "outbound-call",
            Self::OutboundReply => "outbound-reply",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for SmsMessageEnumDirection {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for SmsMessageEnumDirection {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "inbound" => Self::Inbound,
            "outbound-api" => Self::OutboundApi,
            "outbound-call" => Self::OutboundCall,
            "outbound-reply" => Self::OutboundReply,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for SmsMessageEnumDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for SmsMessageEnumDirection {
    fn default() -> SmsMessageEnumDirection {
        Self::Inbound
    }
}
