// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum SmsMessageEnumStatus {
    Queued,
    Sending,
    Sent,
    Failed,
    Delivered,
    Undelivered,
    Receiving,
    Received,
    Accepted,
    Scheduled,
    Read,
    PartiallyDelivered,
    Canceled,

    Unknown(String),
}

impl SmsMessageEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Queued => "queued",
            Self::Sending => "sending",
            Self::Sent => "sent",
            Self::Failed => "failed",
            Self::Delivered => "delivered",
            Self::Undelivered => "undelivered",
            Self::Receiving => "receiving",
            Self::Received => "received",
            Self::Accepted => "accepted",
            Self::Scheduled => "scheduled",
            Self::Read => "read",
            Self::PartiallyDelivered => "partially_delivered",
            Self::Canceled => "canceled",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for SmsMessageEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for SmsMessageEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "queued" => Self::Queued,
            "sending" => Self::Sending,
            "sent" => Self::Sent,
            "failed" => Self::Failed,
            "delivered" => Self::Delivered,
            "undelivered" => Self::Undelivered,
            "receiving" => Self::Receiving,
            "received" => Self::Received,
            "accepted" => Self::Accepted,
            "scheduled" => Self::Scheduled,
            "read" => Self::Read,
            "partially_delivered" => Self::PartiallyDelivered,
            "canceled" => Self::Canceled,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for SmsMessageEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for SmsMessageEnumStatus {
    fn default() -> SmsMessageEnumStatus {
        Self::Queued
    }
}
