// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum SmsFeedbackEnumOutcome {
    Confirmed,
    Unconfirmed,
    Received,
    NotReceived,
    Delayed,

    Unknown(String),
}

impl SmsFeedbackEnumOutcome {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Confirmed => "confirmed",
            Self::Unconfirmed => "unconfirmed",
            Self::Received => "received",
            Self::NotReceived => "not-received",
            Self::Delayed => "delayed",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for SmsFeedbackEnumOutcome {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for SmsFeedbackEnumOutcome {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "confirmed" => Self::Confirmed,
            "unconfirmed" => Self::Unconfirmed,
            "received" => Self::Received,
            "not-received" => Self::NotReceived,
            "delayed" => Self::Delayed,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for SmsFeedbackEnumOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for SmsFeedbackEnumOutcome {
    fn default() -> SmsFeedbackEnumOutcome {
        Self::Confirmed
    }
}
