// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// TranscriptionEnumStatus : The status of the transcription. Can be: `in-progress`, `completed`, `failed`.
/// The status of the transcription. Can be: `in-progress`, `completed`, `failed`.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum TranscriptionEnumStatus {
    InProgress,
    Completed,
    Failed,

    Unknown(String),
}

impl TranscriptionEnumStatus {
    pub fn as_str(&self) -> &str {
        match self {
            Self::InProgress => "in-progress",
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for TranscriptionEnumStatus {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TranscriptionEnumStatus {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "in-progress" => Self::InProgress,
            "completed" => Self::Completed,
            "failed" => Self::Failed,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for TranscriptionEnumStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for TranscriptionEnumStatus {
    fn default() -> TranscriptionEnumStatus {
        Self::InProgress
    }
}
