// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccount409Response {
    /// Twilio-specific error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// Error message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Link to Error Code References
    #[serde(rename = "more_info", skip_serializing_if = "Option::is_none")]
    pub more_info: Option<String>,
    /// HTTP response status code
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
}

impl UpdateAccount409Response {
    pub fn new() -> UpdateAccount409Response {
        UpdateAccount409Response {
            code: None,
            message: None,
            more_info: None,
            status: None,
        }
    }
}
