// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// UsageTriggerEnumRecurring : The frequency of a recurring UsageTrigger.  Can be: `daily`, `monthly`, or `yearly` for recurring triggers or empty for non-recurring triggers. A trigger will only fire once during each period. Recurring times are in GMT.
/// The frequency of a recurring UsageTrigger.  Can be: `daily`, `monthly`, or `yearly` for recurring triggers or empty for non-recurring triggers. A trigger will only fire once during each period. Recurring times are in GMT.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum UsageTriggerEnumRecurring {
    Daily,
    Monthly,
    Yearly,
    Alltime,

    Unknown(String),
}

impl UsageTriggerEnumRecurring {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Daily => "daily",
            Self::Monthly => "monthly",
            Self::Yearly => "yearly",
            Self::Alltime => "alltime",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for UsageTriggerEnumRecurring {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for UsageTriggerEnumRecurring {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "daily" => Self::Daily,
            "monthly" => Self::Monthly,
            "yearly" => Self::Yearly,
            "alltime" => Self::Alltime,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for UsageTriggerEnumRecurring {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for UsageTriggerEnumRecurring {
    fn default() -> UsageTriggerEnumRecurring {
        Self::Daily
    }
}
