// @generated by OpenAPI Generator 7.25.0 for dialkit.
// DO NOT EDIT: update codegen inputs or templates and run codegen/regenerate.sh.

use crate::models;
use serde::{Deserialize, Serialize};

/// UsageTriggerEnumTriggerField : The field in the [UsageRecord](https://www.twilio.com/docs/usage/api/usage-record) resource that fires the trigger.  Can be: `count`, `usage`, or `price`, as described in the [UsageRecords documentation](https://www.twilio.com/docs/usage/api/usage-record#usage-count-price).
/// The field in the [UsageRecord](https://www.twilio.com/docs/usage/api/usage-record) resource that fires the trigger.  Can be: `count`, `usage`, or `price`, as described in the [UsageRecords documentation](https://www.twilio.com/docs/usage/api/usage-record#usage-count-price).
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum UsageTriggerEnumTriggerField {
    Count,
    Usage,
    Price,

    Unknown(String),
}

impl UsageTriggerEnumTriggerField {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Count => "count",
            Self::Usage => "usage",
            Self::Price => "price",
            Self::Unknown(value) => value,
        }
    }
}

impl Serialize for UsageTriggerEnumTriggerField {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for UsageTriggerEnumTriggerField {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "count" => Self::Count,
            "usage" => Self::Usage,
            "price" => Self::Price,
            _ => Self::Unknown(value),
        })
    }
}

impl std::fmt::Display for UsageTriggerEnumTriggerField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Default for UsageTriggerEnumTriggerField {
    fn default() -> UsageTriggerEnumTriggerField {
        Self::Count
    }
}
